from sqlalchemy.orm import Session

from app import models


def thumb(seed: str, w: int = 300, h: int = 400) -> str:
    return f"https://picsum.photos/seed/{seed}/{w}/{h}"


SEED_TEMPLATES = [
    {
        "id": "tpl-poster-sale",
        "name": "促销海报",
        "category": "广告设计",
        "scene": "促销活动",
        "industry": "电商零售",
        "canvas_width": 600,
        "canvas_height": 800,
        "background": "#fef3c7",
        "thumbnail": thumb("sale-poster"),
        "elements": [
            {"type": "image", "x": 0, "y": 0, "width": 600, "height": 400, "src": thumb("sale-poster-bg", 600, 400)},
            {"type": "text", "x": 40, "y": 430, "width": 520, "text": "全场大促", "fontSize": 56, "fontWeight": "bold", "color": "#dc2626", "align": "center"},
            {"type": "text", "x": 40, "y": 510, "width": 520, "text": "低至 3 折起", "fontSize": 28, "color": "#78350f", "align": "center"},
            {"type": "rect", "x": 200, "y": 600, "width": 200, "height": 56, "fill": "#dc2626", "rx": 28},
            {"type": "text", "x": 200, "y": 616, "width": 200, "text": "立即抢购", "fontSize": 22, "color": "#ffffff", "align": "center"},
        ],
    },
    {
        "id": "tpl-flyer-open",
        "name": "开业宣传单",
        "category": "宣传海报",
        "scene": "开业宣传",
        "industry": "餐饮美食",
        "canvas_width": 600,
        "canvas_height": 800,
        "background": "#dbeafe",
        "thumbnail": thumb("open-flyer"),
        "elements": [
            {"type": "text", "x": 40, "y": 60, "width": 520, "text": "盛大开业", "fontSize": 48, "fontWeight": "bold", "color": "#1d4ed8", "align": "center"},
            {"type": "image", "x": 60, "y": 160, "width": 480, "height": 360, "src": thumb("open-flyer-bg", 480, 360)},
            {"type": "text", "x": 40, "y": 560, "width": 520, "text": "开业期间全场 8 折", "fontSize": 26, "color": "#1e3a8a", "align": "center"},
            {"type": "text", "x": 40, "y": 700, "width": 520, "text": "地址：XX市XX路XX号", "fontSize": 18, "color": "#374151", "align": "center"},
        ],
    },
    {
        "id": "tpl-print-menu",
        "name": "菜单印刷",
        "category": "印刷制品",
        "scene": "门店物料",
        "industry": "餐饮美食",
        "canvas_width": 600,
        "canvas_height": 800,
        "background": "#fff7ed",
        "thumbnail": thumb("menu-print"),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 600, "height": 120, "fill": "#ea580c"},
            {"type": "text", "x": 40, "y": 40, "width": 520, "text": "菜单", "fontSize": 40, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 60, "y": 160, "width": 480, "text": "招牌菜品 A ........ 38", "fontSize": 20, "color": "#374151"},
            {"type": "text", "x": 60, "y": 210, "width": 480, "text": "招牌菜品 B ........ 28", "fontSize": 20, "color": "#374151"},
            {"type": "text", "x": 60, "y": 260, "width": 480, "text": "招牌菜品 C ........ 18", "fontSize": 20, "color": "#374151"},
            {"type": "image", "x": 60, "y": 340, "width": 480, "height": 300, "src": thumb("menu-print-bg", 480, 300)},
        ],
    },
    {
        "id": "tpl-ecom-banner",
        "name": "电商主图",
        "category": "电商营销",
        "scene": "促销活动",
        "industry": "电商零售",
        "canvas_width": 800,
        "canvas_height": 800,
        "background": "#f0fdf4",
        "thumbnail": thumb("ecom-banner", 300, 300),
        "elements": [
            {"type": "image", "x": 0, "y": 0, "width": 800, "height": 800, "src": thumb("ecom-banner-bg", 800, 800)},
            {"type": "rect", "x": 40, "y": 40, "width": 260, "height": 80, "fill": "#16a34a", "rx": 16},
            {"type": "text", "x": 40, "y": 62, "width": 260, "text": "新品上市", "fontSize": 28, "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 40, "y": 680, "width": 720, "text": "限时特惠 ¥99", "fontSize": 44, "fontWeight": "bold", "color": "#166534", "align": "center"},
        ],
    },
    {
        "id": "tpl-social-post",
        "name": "公众号封面",
        "category": "自媒体配图",
        "scene": "内容封面",
        "industry": "通用场景",
        "canvas_width": 900,
        "canvas_height": 500,
        "background": "#ede9fe",
        "thumbnail": thumb("social-post", 300, 167),
        "elements": [
            {"type": "image", "x": 0, "y": 0, "width": 900, "height": 500, "src": thumb("social-post-bg", 900, 500)},
            {"type": "rect", "x": 0, "y": 380, "width": 900, "height": 120, "fill": "rgba(0,0,0,0.45)"},
            {"type": "text", "x": 40, "y": 410, "width": 820, "text": "在这里输入你的标题", "fontSize": 36, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
        ],
    },
    {
        "id": "tpl-card-thankyou",
        "name": "感谢卡",
        "category": "宣传海报",
        "scene": "感恩贺卡",
        "industry": "通用场景",
        "canvas_width": 600,
        "canvas_height": 800,
        "background": "#fce7f3",
        "thumbnail": thumb("thankyou-card"),
        "elements": [
            {"type": "text", "x": 40, "y": 80, "width": 520, "text": "Thank You", "fontSize": 44, "fontWeight": "bold", "color": "#be185d", "align": "center"},
            {"type": "image", "x": 100, "y": 200, "width": 400, "height": 400, "src": thumb("thankyou-card-bg", 400, 400)},
            {"type": "text", "x": 40, "y": 640, "width": 520, "text": "感谢一路有你", "fontSize": 24, "color": "#831843", "align": "center"},
        ],
    },
    {
        "id": "tpl-handnews-traffic",
        "name": "交通安全手抄报",
        "category": "创意手作",
        "scene": "校园手抄报",
        "industry": "教育培训",
        "canvas_width": 700,
        "canvas_height": 900,
        "background": "#dbeafe",
        "thumbnail": thumb("handnews-traffic", 300, 386),
        "elements": [
            {"type": "image", "x": 0, "y": 0, "width": 700, "height": 380, "src": thumb("handnews-traffic-bg", 700, 380)},
            {"type": "text", "x": 40, "y": 400, "width": 620, "text": "交通安全", "fontSize": 64, "fontWeight": "bold", "color": "#dc2626", "align": "center"},
            {"type": "rect", "x": 40, "y": 500, "width": 290, "height": 350, "fill": "#ffffff", "rx": 20},
            {"type": "rect", "x": 370, "y": 500, "width": 290, "height": 350, "fill": "#ffffff", "rx": 20},
            {"type": "text", "x": 60, "y": 530, "width": 250, "text": "1.要走人行道，没\n有人行道时靠边\n走。\n2.结伴外出时，不\n打闹嬉戏。\n3.过马路时不看手\n机，注意观察车辆", "fontSize": 20, "color": "#1f2937"},
            {"type": "text", "x": 390, "y": 530, "width": 250, "text": "骑车出行要戴头\n盔，不可载人，\n出行前检查车\n辆，不逆行，应\n走非机动车道", "fontSize": 20, "color": "#1f2937"},
        ],
    },
    {
        "id": "tpl-handnews-reading",
        "name": "读书手抄报",
        "category": "创意手作",
        "scene": "校园手抄报",
        "industry": "教育培训",
        "canvas_width": 700,
        "canvas_height": 900,
        "background": "#fef9e7",
        "thumbnail": thumb("handnews-reading", 300, 386),
        "elements": [
            {"type": "image", "x": 60, "y": 40, "width": 580, "height": 320, "src": thumb("handnews-reading-bg", 580, 320)},
            {"type": "text", "x": 40, "y": 380, "width": 620, "text": "好书伴我成长", "fontSize": 56, "fontWeight": "bold", "color": "#b45309", "align": "center"},
            {"type": "rect", "x": 40, "y": 470, "width": 620, "height": 180, "fill": "#ffffff", "rx": 20},
            {"type": "text", "x": 70, "y": 500, "width": 560, "text": "推荐理由：这本书教会我遇到困难\n不放弃，主人公勇敢善良的品质\n很值得我们学习。", "fontSize": 22, "color": "#374151"},
            {"type": "rect", "x": 40, "y": 680, "width": 620, "height": 180, "fill": "#ffffff", "rx": 20},
            {"type": "text", "x": 70, "y": 710, "width": 560, "text": "读后感：读完这本书，我明白了坚\n持的意义，以后我也要做一个不\n轻言放弃的人。", "fontSize": 22, "color": "#374151"},
        ],
    },
    {
        "id": "tpl-office-resume",
        "name": "个人简历",
        "category": "职场文档",
        "scene": "简历文档",
        "industry": "企业办公",
        "canvas_width": 700,
        "canvas_height": 950,
        "background": "#ffffff",
        "thumbnail": thumb("office-resume", 300, 407),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 700, "height": 150, "fill": "#1f2937"},
            {"type": "text", "x": 40, "y": 30, "width": 500, "text": "张三", "fontSize": 36, "fontWeight": "bold", "color": "#ffffff"},
            {"type": "text", "x": 40, "y": 86, "width": 500, "text": "求职意向：前端开发工程师", "fontSize": 18, "color": "#dbeafe"},
            {"type": "text", "x": 40, "y": 118, "width": 600, "text": "138-0000-0000  |  zhangsan@email.com  |  北京", "fontSize": 14, "color": "#9ca3af"},
            {"type": "rect", "x": 40, "y": 190, "width": 6, "height": 24, "fill": "#2563eb"},
            {"type": "text", "x": 60, "y": 188, "width": 300, "text": "教育经历", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 232, "width": 500, "text": "北京大学  ·  计算机科学与技术  ·  本科", "fontSize": 16, "color": "#374151"},
            {"type": "text", "x": 40, "y": 258, "width": 500, "text": "2018.09 - 2022.06", "fontSize": 14, "color": "#9ca3af"},
            {"type": "rect", "x": 40, "y": 310, "width": 6, "height": 24, "fill": "#2563eb"},
            {"type": "text", "x": 60, "y": 308, "width": 300, "text": "工作经历", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 352, "width": 500, "text": "某某科技有限公司  ·  前端开发工程师", "fontSize": 16, "color": "#374151"},
            {"type": "text", "x": 40, "y": 378, "width": 500, "text": "2022.07 - 至今", "fontSize": 14, "color": "#9ca3af"},
            {"type": "text", "x": 40, "y": 408, "width": 620, "text": "• 负责公司核心产品的前端架构设计与开发\n• 主导性能优化专项，首屏加载速度提升 40%\n• 带领 3 人小组完成组件库建设，提升团队协作效率", "fontSize": 16, "color": "#374151"},
            {"type": "rect", "x": 40, "y": 540, "width": 6, "height": 24, "fill": "#2563eb"},
            {"type": "text", "x": 60, "y": 538, "width": 300, "text": "技能特长", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 582, "width": 620, "text": "• 熟练掌握 Vue3 / React / TypeScript\n• 熟悉前端工程化、性能优化与自动化测试\n• 良好的沟通表达与团队协作能力", "fontSize": 16, "color": "#374151"},
            {"type": "rect", "x": 40, "y": 712, "width": 6, "height": 24, "fill": "#2563eb"},
            {"type": "text", "x": 60, "y": 710, "width": 300, "text": "自我评价", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 754, "width": 620, "text": "工作认真负责，学习能力强，能够快速适应新\n技术栈，具备良好的问题排查与解决能力。", "fontSize": 16, "color": "#374151"},
        ],
    },
    {
        "id": "tpl-office-leave",
        "name": "请假条",
        "category": "职场文档",
        "scene": "通知公文",
        "industry": "企业办公",
        "canvas_width": 700,
        "canvas_height": 700,
        "background": "#ffffff",
        "thumbnail": thumb("office-leave", 300, 300),
        "elements": [
            {"type": "text", "x": 40, "y": 50, "width": 620, "text": "请假条", "fontSize": 40, "fontWeight": "bold", "color": "#1f2937", "align": "center"},
            {"type": "rect", "x": 260, "y": 112, "width": 180, "height": 3, "fill": "#9ca3af"},
            {"type": "text", "x": 60, "y": 170, "width": 580, "text": "尊敬的领导：", "fontSize": 18, "color": "#374151"},
            {"type": "text", "x": 60, "y": 216, "width": 580, "text": "本人因＿＿＿＿＿＿＿＿＿＿＿＿＿＿事由，\n需请假＿＿天，自＿＿＿＿年＿＿月＿＿日起，\n至＿＿＿＿年＿＿月＿＿日止，请予批准。", "fontSize": 18, "color": "#374151"},
            {"type": "text", "x": 60, "y": 360, "width": 580, "text": "特此申请，谢谢！", "fontSize": 18, "color": "#374151"},
            {"type": "text", "x": 60, "y": 560, "width": 400, "text": "申请人：＿＿＿＿＿＿", "fontSize": 18, "color": "#1f2937"},
            {"type": "text", "x": 60, "y": 604, "width": 400, "text": "日 期：＿＿＿＿年＿＿月＿＿日", "fontSize": 18, "color": "#1f2937"},
            {"type": "text", "x": 380, "y": 560, "width": 280, "text": "部门负责人：＿＿＿＿＿＿", "fontSize": 18, "color": "#1f2937"},
        ],
    },
    {
        "id": "tpl-office-meeting",
        "name": "会议通知",
        "category": "职场文档",
        "scene": "通知公文",
        "industry": "企业办公",
        "canvas_width": 700,
        "canvas_height": 780,
        "background": "#ffffff",
        "thumbnail": thumb("office-meeting", 300, 334),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 700, "height": 96, "fill": "#0f766e"},
            {"type": "text", "x": 40, "y": 30, "width": 620, "text": "会议通知", "fontSize": 32, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 60, "y": 136, "width": 580, "text": "各部门负责人：\n兹定于近期召开月度工作总结会议，请相关\n人员准时参加，具体安排如下：", "fontSize": 18, "color": "#1f2937"},
            {"type": "rect", "x": 60, "y": 260, "width": 580, "height": 220, "fill": "#f0fdfa", "rx": 12},
            {"type": "text", "x": 90, "y": 288, "width": 520, "text": "时间：＿＿＿＿年＿＿月＿＿日 ＿＿:＿＿", "fontSize": 18, "color": "#0f766e", "fontWeight": "bold"},
            {"type": "text", "x": 90, "y": 328, "width": 520, "text": "地点：公司三楼会议室", "fontSize": 18, "color": "#0f766e", "fontWeight": "bold"},
            {"type": "text", "x": 90, "y": 368, "width": 520, "text": "参会人员：各部门负责人", "fontSize": 18, "color": "#0f766e", "fontWeight": "bold"},
            {"type": "text", "x": 90, "y": 408, "width": 520, "text": "会议主题：月度工作总结", "fontSize": 18, "color": "#0f766e", "fontWeight": "bold"},
            {"type": "text", "x": 60, "y": 520, "width": 580, "text": "请与会人员提前做好相关准备工作，如有特殊\n情况无法参加，请提前向行政部请假。", "fontSize": 16, "color": "#374151"},
            {"type": "text", "x": 300, "y": 660, "width": 340, "text": "XX 公司行政部", "fontSize": 16, "color": "#1f2937", "align": "right"},
            {"type": "text", "x": 300, "y": 690, "width": 340, "text": "＿＿＿＿年＿＿月＿＿日", "fontSize": 16, "color": "#1f2937", "align": "right"},
        ],
    },
    {
        "id": "tpl-office-invitation",
        "name": "邀请函",
        "category": "职场文档",
        "scene": "邀请函卡",
        "industry": "企业办公",
        "canvas_width": 700,
        "canvas_height": 900,
        "background": "#1e293b",
        "thumbnail": thumb("office-invitation", 300, 386),
        "elements": [
            {"type": "rect", "x": 30, "y": 30, "width": 640, "height": 4, "fill": "#d4af37"},
            {"type": "rect", "x": 30, "y": 866, "width": 640, "height": 4, "fill": "#d4af37"},
            {"type": "rect", "x": 30, "y": 30, "width": 4, "height": 840, "fill": "#d4af37"},
            {"type": "rect", "x": 666, "y": 30, "width": 4, "height": 840, "fill": "#d4af37"},
            {"type": "text", "x": 40, "y": 130, "width": 620, "text": "邀 请 函", "fontSize": 46, "fontWeight": "bold", "color": "#d4af37", "align": "center"},
            {"type": "text", "x": 40, "y": 196, "width": 620, "text": "I N V I T A T I O N", "fontSize": 14, "color": "#d4af37", "align": "center"},
            {"type": "text", "x": 70, "y": 320, "width": 560, "text": "尊敬的＿＿＿＿＿＿ 先生/女士：", "fontSize": 20, "color": "#e2e8f0"},
            {"type": "text", "x": 70, "y": 370, "width": 560, "text": "诚挚邀请您拨冗出席我们的年度盛典，\n期待您的莅临与支持，共襄盛举。", "fontSize": 18, "color": "#cbd5e1"},
            {"type": "rect", "x": 70, "y": 500, "width": 560, "height": 2, "fill": "#475569"},
            {"type": "text", "x": 70, "y": 540, "width": 560, "text": "时间：＿＿＿＿年＿＿月＿＿日 ＿＿:＿＿", "fontSize": 18, "color": "#e2e8f0"},
            {"type": "text", "x": 70, "y": 580, "width": 560, "text": "地点：＿＿＿＿＿＿＿＿＿＿＿＿＿＿", "fontSize": 18, "color": "#e2e8f0"},
            {"type": "text", "x": 70, "y": 620, "width": 560, "text": "主办方：＿＿＿＿＿＿＿＿＿＿＿＿", "fontSize": 18, "color": "#e2e8f0"},
            {"type": "text", "x": 70, "y": 780, "width": 560, "text": "敬请回复", "fontSize": 16, "color": "#94a3b8"},
        ],
    },
    {
        "id": "tpl-board-safety-month",
        "name": "安全生产月宣传展板",
        "category": "广告设计",
        "scene": "宣传展板",
        "industry": "企业办公",
        "canvas_width": 1200,
        "canvas_height": 970,
        "background": "#ffffff",
        "thumbnail": thumb("board-safety-month", 300, 242),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 1200, "height": 150, "fill": "#c1272d"},
            {"type": "text", "x": 0, "y": 32, "width": 1200, "text": "全国安全生产月", "fontSize": 52, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 100, "width": 1200, "text": "第25个全国「安全生产月」 · 2026年6月", "fontSize": 20, "color": "#fde8e8", "align": "center"},
            {"type": "rect", "x": 60, "y": 170, "width": 1080, "height": 70, "fill": "#fef3c7", "rx": 10},
            {"type": "text", "x": 60, "y": 190, "width": 1080, "text": "人人讲安全、个个会应急——排查整治风险隐患", "fontSize": 26, "fontWeight": "bold", "color": "#92400e", "align": "center"},
            {"type": "rect", "x": 60, "y": 270, "width": 530, "height": 190, "fill": "#f9fafb", "rx": 12},
            {"type": "text", "x": 88, "y": 296, "width": 474, "text": "消防安全 · 应急逃生", "fontSize": 23, "fontWeight": "bold", "color": "#dc2626"},
            {"type": "text", "x": 88, "y": 340, "width": 474, "text": "学习掌握火灾逃生、用电用气、电动自行车充电安全常识，清理占用疏散通道、堆放易燃物品等隐患，确保安全通道畅通无阻。", "fontSize": 17, "color": "#374151"},
            {"type": "rect", "x": 610, "y": 270, "width": 530, "height": 190, "fill": "#f9fafb", "rx": 12},
            {"type": "text", "x": 638, "y": 296, "width": 474, "text": "风险隐患排查整治", "fontSize": 23, "fontWeight": "bold", "color": "#ea580c"},
            {"type": "text", "x": 638, "y": 340, "width": 474, "text": "聚焦矿山、危险化学品、建筑施工、交通运输、工贸、燃气、消防等重点行业领域，全面排查整治各类安全风险隐患。", "fontSize": 17, "color": "#374151"},
            {"type": "rect", "x": 60, "y": 480, "width": 1080, "height": 190, "fill": "#f9fafb", "rx": 12},
            {"type": "rect", "x": 88, "y": 506, "width": 8, "height": 24, "fill": "#c1272d"},
            {"type": "text", "x": 104, "y": 504, "width": 200, "text": "五落实", "fontSize": 22, "fontWeight": "bold", "color": "#c1272d"},
            {"type": "text", "x": 88, "y": 546, "width": 474, "text": "1. 必须落实「党政同责」要求", "fontSize": 15, "color": "#374151"},
            {"type": "text", "x": 88, "y": 576, "width": 474, "text": "2. 必须落实安全生产「一岗双责」", "fontSize": 15, "color": "#374151"},
            {"type": "text", "x": 88, "y": 606, "width": 474, "text": "3. 必须落实安全生产组织领导机构", "fontSize": 15, "color": "#374151"},
            {"type": "text", "x": 88, "y": 636, "width": 474, "text": "4. 必须落实安全管理力量", "fontSize": 15, "color": "#374151"},
            {"type": "rect", "x": 638, "y": 506, "width": 8, "height": 24, "fill": "#2563eb"},
            {"type": "text", "x": 654, "y": 504, "width": 200, "text": "五到位", "fontSize": 22, "fontWeight": "bold", "color": "#2563eb"},
            {"type": "text", "x": 638, "y": 546, "width": 474, "text": "1. 安全责任到位  2. 安全投入到位", "fontSize": 15, "color": "#374151"},
            {"type": "text", "x": 638, "y": 576, "width": 474, "text": "3. 安全培训到位  4. 安全管理到位", "fontSize": 15, "color": "#374151"},
            {"type": "text", "x": 638, "y": 606, "width": 474, "text": "5. 应急救援到位", "fontSize": 15, "color": "#374151"},
            {"type": "text", "x": 638, "y": 636, "width": 474, "text": "五个方面同步到位，一处不落", "fontSize": 15, "color": "#9ca3af"},
            {"type": "rect", "x": 60, "y": 690, "width": 530, "height": 190, "fill": "#f9fafb", "rx": 12},
            {"type": "text", "x": 88, "y": 716, "width": 474, "text": "人人会应急", "fontSize": 23, "fontWeight": "bold", "color": "#2563eb"},
            {"type": "text", "x": 88, "y": 760, "width": 474, "text": "普及基本应急救护和避险技能，做到早发现、早报告、早处置，提升自救互救能力，筑牢身边的安全防线。", "fontSize": 17, "color": "#374151"},
            {"type": "rect", "x": 610, "y": 690, "width": 530, "height": 190, "fill": "#f9fafb", "rx": 12},
            {"type": "text", "x": 638, "y": 716, "width": 474, "text": "安全第一 入脑入心", "fontSize": 23, "fontWeight": "bold", "color": "#16a34a"},
            {"type": "text", "x": 638, "y": 760, "width": 474, "text": "每个人都是安全防线，每个岗位都是安全哨点。树牢安全发展理念，把安全生产责任落实到每一个岗位、每一个环节。", "fontSize": 17, "color": "#374151"},
            {"type": "text", "x": 0, "y": 910, "width": 1200, "text": "6 月 16 日 全国安全宣传咨询日", "fontSize": 18, "color": "#6b7280", "align": "center"},
            {"type": "text", "x": 700, "y": 940, "width": 440, "text": "＿＿＿＿＿＿＿＿ 单位  制", "fontSize": 16, "color": "#9ca3af", "align": "right"},
        ],
    },
    {
        "id": "tpl-board-safety-month-grid",
        "name": "安全生产月信息看板",
        "category": "广告设计",
        "scene": "宣传展板",
        "industry": "企业办公",
        "canvas_width": 1600,
        "canvas_height": 1020,
        "background": "#fdf6ec",
        "thumbnail": thumb("board-safety-month-grid", 300, 191),
        "elements": [
            {"type": "image", "x": 0, "y": 0, "width": 1600, "height": 1020, "src": "/templates/safety-month-grid-bg.png"},
            {"type": "rect", "x": 0, "y": 0, "width": 1600, "height": 130, "fill": "#c1272d"},
            {"type": "text", "x": 0, "y": 30, "width": 1600, "text": "2026年企业安全生产宣传月", "fontSize": 46, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 92, "width": 1600, "text": "凝聚全员合力 · 共筑安全防线", "fontSize": 18, "color": "#fde8e8", "align": "center"},
            {"type": "rect", "x": 90, "y": 190, "width": 140, "height": 36, "fill": "#fbbf24", "rx": 18},
            {"type": "text", "x": 90, "y": 198, "width": 140, "text": "宣传主题", "fontSize": 15, "fontWeight": "bold", "color": "#7c2d12", "align": "center"},
            {"type": "rect", "x": 90, "y": 240, "width": 1420, "height": 76, "fill": "#fef3c7", "rx": 12},
            {"type": "text", "x": 90, "y": 264, "width": 1420, "text": "凝聚全员合力，排查化解风险隐患，共筑安全生产防线", "fontSize": 25, "fontWeight": "bold", "color": "#92400e", "align": "center"},
            {"type": "text", "x": 1200, "y": 326, "width": 310, "text": "宣传张贴 · 请妥善保管", "fontSize": 13, "color": "#9ca3af", "align": "right"},
            {"type": "rect", "x": 76, "y": 350, "width": 248, "height": 156, "fill": "#f9fafb", "rx": 10},
            {"type": "rect", "x": 90, "y": 366, "width": 6, "height": 22, "fill": "#c1272d"},
            {"type": "text", "x": 106, "y": 363, "width": 204, "text": "缘起与目的", "fontSize": 16, "fontWeight": "bold", "color": "#c1272d"},
            {"type": "text", "x": 90, "y": 410, "width": 204, "text": "安全生产月每年6月举行，聚焦重大风险隐患排查，推动企业压实主体责任，提升全员安全防护能力。", "fontSize": 13, "color": "#374151"},
            {"type": "rect", "x": 76, "y": 530, "width": 248, "height": 236, "fill": "#f9fafb", "rx": 10},
            {"type": "rect", "x": 90, "y": 546, "width": 6, "height": 22, "fill": "#c1272d"},
            {"type": "text", "x": 106, "y": 543, "width": 204, "text": "开展的意义", "fontSize": 16, "fontWeight": "bold", "color": "#c1272d"},
            {"type": "group", "x": 90, "y": 590, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#c1272d", "icon": "1", "label": "普及安全知识 提升防护意识"}, {"shape": "circle", "color": "#c1272d", "icon": "2", "label": "排查身边隐患 防止小患成灾"}, {"shape": "circle", "color": "#c1272d", "icon": "3", "label": "压实岗位责任 人人守好一段"}, {"shape": "circle", "color": "#c1272d", "icon": "4", "label": "沉淀应急经验 遇险不慌自救"}]},
                        {"type": "image", "x": 146, "y": 768, "width": 106, "height": 160, "src": "/templates/safety-month-grid-worker-icon.png"},
            {"type": "rect", "x": 316, "y": 350, "width": 248, "height": 236, "fill": "#f9fafb", "rx": 10},
            {"type": "rect", "x": 330, "y": 366, "width": 6, "height": 22, "fill": "#2563eb"},
            {"type": "text", "x": 346, "y": 363, "width": 204, "text": "责任落实要点", "fontSize": 16, "fontWeight": "bold", "color": "#2563eb"},
            {"type": "group", "x": 330, "y": 410, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#2563eb", "icon": "1", "label": "党政同责 一岗双责不缺位"}, {"shape": "circle", "color": "#2563eb", "icon": "2", "label": "齐抓共管 各司其责不推诿"}, {"shape": "circle", "color": "#2563eb", "icon": "3", "label": "责任到人 签字背书不虚化"}, {"shape": "circle", "color": "#2563eb", "icon": "4", "label": "层层传导 末端发力不悬空"}]},
                        {"type": "rect", "x": 316, "y": 610, "width": 248, "height": 236, "fill": "#f9fafb", "rx": 10},
            {"type": "rect", "x": 330, "y": 626, "width": 6, "height": 22, "fill": "#16a34a"},
            {"type": "text", "x": 346, "y": 623, "width": 204, "text": "落实要到位", "fontSize": 16, "fontWeight": "bold", "color": "#16a34a"},
            {"type": "group", "x": 330, "y": 670, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#16a34a", "icon": "1", "label": "责任到位 权责边界要清楚"}, {"shape": "circle", "color": "#16a34a", "icon": "2", "label": "投入到位 安全经费不克扣"}, {"shape": "circle", "color": "#16a34a", "icon": "3", "label": "培训到位 持证上岗不走场"}, {"shape": "circle", "color": "#16a34a", "icon": "4", "label": "应急到位 预案演练不摆设"}]},
                        {"type": "rect", "x": 556, "y": 350, "width": 248, "height": 236, "fill": "#f9fafb", "rx": 10},
            {"type": "rect", "x": 570, "y": 366, "width": 6, "height": 22, "fill": "#dc2626"},
            {"type": "text", "x": 586, "y": 363, "width": 204, "text": "四条不能碰", "fontSize": 16, "fontWeight": "bold", "color": "#dc2626"},
            {"type": "group", "x": 570, "y": 410, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#dc2626", "icon": "✕", "label": "安全规程不能违"}, {"shape": "circle", "color": "#dc2626", "icon": "✕", "label": "安全教育不能缺"}, {"shape": "circle", "color": "#dc2626", "icon": "✕", "label": "安全投入不能省"}, {"shape": "circle", "color": "#dc2626", "icon": "✕", "label": "安全管理不能松"}]},
                        {"type": "rect", "x": 556, "y": 610, "width": 248, "height": 236, "fill": "#f9fafb", "rx": 10},
            {"type": "rect", "x": 570, "y": 626, "width": 6, "height": 22, "fill": "#16a34a"},
            {"type": "text", "x": 586, "y": 623, "width": 204, "text": "四句要记牢", "fontSize": 16, "fontWeight": "bold", "color": "#16a34a"},
            {"type": "group", "x": 570, "y": 670, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#16a34a", "icon": "✓", "label": "隐患不过夜 发现即整改"}, {"shape": "circle", "color": "#16a34a", "icon": "✓", "label": "违章不放过 纠正再复工"}, {"shape": "circle", "color": "#16a34a", "icon": "✓", "label": "交接不马虎 班前班后查"}, {"shape": "circle", "color": "#16a34a", "icon": "✓", "label": "应急不侥幸 预案记在心"}]},
                        {"type": "rect", "x": 796, "y": 350, "width": 248, "height": 236, "fill": "#f9fafb", "rx": 10},
            {"type": "rect", "x": 810, "y": 366, "width": 6, "height": 22, "fill": "#2563eb"},
            {"type": "text", "x": 826, "y": 363, "width": 204, "text": "八字工作法", "fontSize": 16, "fontWeight": "bold", "color": "#2563eb"},
            {"type": "group", "x": 810, "y": 410, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#2563eb", "icon": "1", "label": "遵章守纪 警钟长鸣"}, {"shape": "circle", "color": "#2563eb", "icon": "2", "label": "谨慎细致 防微杜渐"}, {"shape": "circle", "color": "#2563eb", "icon": "3", "label": "精力集中 事前预防"}, {"shape": "circle", "color": "#2563eb", "icon": "4", "label": "劳保穿戴 严格要求"}]},
                        {"type": "rect", "x": 796, "y": 610, "width": 248, "height": 236, "fill": "#f9fafb", "rx": 10},
            {"type": "rect", "x": 810, "y": 626, "width": 6, "height": 22, "fill": "#ea580c"},
            {"type": "text", "x": 826, "y": 623, "width": 204, "text": "八项危险源", "fontSize": 16, "fontWeight": "bold", "color": "#ea580c"},
            {"type": "group", "x": 810, "y": 670, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#ea580c", "icon": "1", "label": "违章指挥 心存侥幸"}, {"shape": "circle", "color": "#ea580c", "icon": "2", "label": "逞强好胜 器具乱用"}, {"shape": "circle", "color": "#ea580c", "icon": "3", "label": "心神不定 事后补救"}, {"shape": "circle", "color": "#ea580c", "icon": "4", "label": "麻痹大意 松松垮垮"}]},
                        {"type": "rect", "x": 1036, "y": 350, "width": 248, "height": 236, "fill": "#f9fafb", "rx": 10},
            {"type": "rect", "x": 1050, "y": 366, "width": 6, "height": 22, "fill": "#c1272d"},
            {"type": "text", "x": 1066, "y": 363, "width": 204, "text": "四个不放过", "fontSize": 16, "fontWeight": "bold", "color": "#c1272d"},
            {"type": "group", "x": 1050, "y": 410, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#c1272d", "icon": "1", "label": "原因不查清不放过"}, {"shape": "circle", "color": "#c1272d", "icon": "2", "label": "责任不追究不放过"}, {"shape": "circle", "color": "#c1272d", "icon": "3", "label": "整改不到位不放过"}, {"shape": "circle", "color": "#c1272d", "icon": "4", "label": "教育不达标不放过"}]},
                        {"type": "rect", "x": 1036, "y": 610, "width": 248, "height": 236, "fill": "#f9fafb", "rx": 10},
            {"type": "rect", "x": 1050, "y": 626, "width": 6, "height": 22, "fill": "#2563eb"},
            {"type": "text", "x": 1066, "y": 623, "width": 204, "text": "现场检查四要点", "fontSize": 16, "fontWeight": "bold", "color": "#2563eb"},
            {"type": "group", "x": 1050, "y": 670, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#16a34a", "icon": "✓", "label": "设施完好 标识清晰"}, {"shape": "circle", "color": "#16a34a", "icon": "✓", "label": "通道畅通 严禁占用"}, {"shape": "circle", "color": "#16a34a", "icon": "✓", "label": "用火用电 规范操作"}, {"shape": "circle", "color": "#16a34a", "icon": "✓", "label": "防护到位 持证上岗"}]},
                        {"type": "rect", "x": 1276, "y": 350, "width": 248, "height": 226, "fill": "#f9fafb", "rx": 10},
            {"type": "rect", "x": 1290, "y": 366, "width": 6, "height": 22, "fill": "#7c3aed"},
            {"type": "text", "x": 1306, "y": 363, "width": 204, "text": "安全生产常用语", "fontSize": 16, "fontWeight": "bold", "color": "#7c3aed"},
            {"type": "text", "x": 1290, "y": 410, "width": 204, "text": "党政同责——党委政府同担责任", "fontSize": 13, "color": "#374151"},
            {"type": "text", "x": 1290, "y": 460, "width": 204, "text": "一岗双责——岗位职责与安全职责一肩挑", "fontSize": 13, "color": "#374151"},
            {"type": "text", "x": 1290, "y": 510, "width": 204, "text": "三个必须——管业务必须管安全", "fontSize": 13, "color": "#374151"},
            {"type": "rect", "x": 1276, "y": 600, "width": 248, "height": 236, "fill": "#f9fafb", "rx": 10},
            {"type": "rect", "x": 1290, "y": 616, "width": 6, "height": 22, "fill": "#ea580c"},
            {"type": "text", "x": 1306, "y": 613, "width": 204, "text": "现场应急四能力", "fontSize": 16, "fontWeight": "bold", "color": "#ea580c"},
            {"type": "group", "x": 1290, "y": 660, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#ea580c", "icon": "1", "label": "排查隐患的能力"}, {"shape": "circle", "color": "#ea580c", "icon": "2", "label": "组织疏散的能力"}, {"shape": "circle", "color": "#ea580c", "icon": "3", "label": "扑救初起火灾能力"}, {"shape": "circle", "color": "#ea580c", "icon": "4", "label": "报告宣传教育能力"}]},
                        {"type": "image", "x": 1368, "y": 838, "width": 64, "height": 96, "src": "/templates/safety-month-grid-inspector-icon.png"},
            {"type": "rect", "x": 0, "y": 940, "width": 1600, "height": 60, "fill": "#c1272d"},
            {"type": "text", "x": 0, "y": 956, "width": 1600, "text": "人人尽责 · 安全你我", "fontSize": 20, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
        ],
    },
    {
        "id": "tpl-ad-realestate",
        "name": "楼盘品鉴海报",
        "category": "广告设计",
        "scene": "宣传展板",
        "industry": "家居地产",
        "canvas_width": 800,
        "canvas_height": 1000,
        "background": "#0f172a",
        "thumbnail": thumb("ad-realestate", 300, 375),
        "elements": [
            {"type": "rect", "x": 60, "y": 60, "width": 680, "height": 3, "fill": "#d4af37"},
            {"type": "rect", "x": 60, "y": 910, "width": 680, "height": 3, "fill": "#d4af37"},
            {"type": "text", "x": 60, "y": 160, "width": 680, "text": "臻藏 · 城市之上", "fontSize": 54, "fontWeight": "bold", "color": "#d4af37", "align": "center"},
            {"type": "text", "x": 60, "y": 240, "width": 680, "text": "臻稀楼王 甄选而生", "fontSize": 20, "color": "#e2e8f0", "align": "center"},
            {"type": "rect", "x": 300, "y": 320, "width": 200, "height": 2, "fill": "#475569"},
            {"type": "text", "x": 100, "y": 400, "width": 600, "text": "地铁上盖 · 双学区配套 · 环城公园首排", "fontSize": 22, "color": "#cbd5e1", "align": "center"},
            {"type": "text", "x": 100, "y": 450, "width": 600, "text": "建面约 89-143㎡ 甄稀墅质大宅", "fontSize": 18, "color": "#94a3b8", "align": "center"},
            {"type": "rect", "x": 300, "y": 780, "width": 200, "height": 60, "fill": "#d4af37", "rx": 4},
            {"type": "text", "x": 300, "y": 798, "width": 200, "text": "预约品鉴", "fontSize": 22, "fontWeight": "bold", "color": "#0f172a", "align": "center"},
            {"type": "text", "x": 60, "y": 860, "width": 680, "text": "咨询热线：400-＿＿＿-＿＿＿＿", "fontSize": 16, "color": "#94a3b8", "align": "center"},
        ],
    },
    {
        "id": "tpl-poster-flash-sale",
        "name": "限时闪购海报",
        "category": "宣传海报",
        "scene": "促销活动",
        "industry": "电商零售",
        "canvas_width": 600,
        "canvas_height": 800,
        "background": "#fff1f2",
        "thumbnail": thumb("poster-flash-sale", 300, 400),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 600, "height": 260, "fill": "#f43f5e"},
            {"type": "text", "x": 0, "y": 50, "width": 600, "text": "周末闪购 48小时", "fontSize": 44, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 130, "width": 600, "text": "低至 5 折 手慢无", "fontSize": 24, "color": "#fff1f2", "align": "center"},
            {"type": "rect", "x": 220, "y": 180, "width": 160, "height": 50, "fill": "#ffffff", "rx": 25},
            {"type": "text", "x": 220, "y": 195, "width": 160, "text": "立即抢购", "fontSize": 20, "fontWeight": "bold", "color": "#f43f5e", "align": "center"},
            {"type": "text", "x": 40, "y": 300, "width": 520, "text": "各品类折扣力度", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {
                "type": "group",
                "x": 40,
                "y": 350,
                "children": [],
                "componentKind": "progress-bars",
                "componentData": [
                    {"label": "服饰", "value": 70, "color": "#f97316"},
                    {"label": "美妆", "value": 55, "color": "#ec4899"},
                    {"label": "数码", "value": 85, "color": "#38bdf8"},
                ],
            },
            {"type": "text", "x": 40, "y": 700, "width": 520, "text": "活动时间：本周六 00:00 - 周日 24:00", "fontSize": 16, "color": "#6b7280", "align": "center"},
        ],
    },
    {
        "id": "tpl-print-pricelist",
        "name": "轻食价目单",
        "category": "印刷制品",
        "scene": "门店物料",
        "industry": "餐饮美食",
        "canvas_width": 600,
        "canvas_height": 850,
        "background": "#fff7ed",
        "thumbnail": thumb("print-pricelist", 300, 425),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 600, "height": 140, "fill": "#f97316"},
            {"type": "text", "x": 0, "y": 45, "width": 600, "text": "轻食价目单", "fontSize": 36, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 95, "width": 600, "text": "新鲜现做 · 健康轻负担", "fontSize": 16, "color": "#ffedd5", "align": "center"},
            {
                "type": "group",
                "x": 165,
                "y": 180,
                "children": [],
                "componentKind": "grid-table",
                "componentData": {
                    "rows": [
                        ["单品", "热量", "价格"],
                        ["轻食沙拉", "320kcal", "28"],
                        ["牛油果虾", "280kcal", "32"],
                        ["低脂鸡卷", "260kcal", "22"],
                        ["鲜榨果昔", "150kcal", "18"],
                    ],
                    "theme": "orange",
                    "fontFamily": "sans-serif",
                    "fontSize": 13,
                    "bold": False,
                    "italic": False,
                    "underline": False,
                    "align": "left",
                    "merges": [],
                },
            },
            {"type": "text", "x": 40, "y": 420, "width": 520, "text": "以上价格仅供参考，具体以门店为准", "fontSize": 14, "color": "#9ca3af", "align": "center"},
            {"type": "rect", "x": 0, "y": 770, "width": 600, "height": 80, "fill": "#f97316"},
            {"type": "text", "x": 0, "y": 800, "width": 600, "text": "地址：XX市XX路轻食生活馆", "fontSize": 16, "color": "#ffffff", "align": "center"},
        ],
    },
    {
        "id": "tpl-ecom-presale",
        "name": "新品预售海报",
        "category": "电商营销",
        "scene": "促销活动",
        "industry": "电商零售",
        "canvas_width": 800,
        "canvas_height": 800,
        "background": "#111827",
        "thumbnail": thumb("ecom-presale", 300, 300),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 800, "height": 8, "fill": "#22d3ee"},
            {"type": "text", "x": 0, "y": 140, "width": 800, "text": "新品预售", "fontSize": 64, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 230, "width": 800, "text": "预售立减 ¥200", "fontSize": 28, "color": "#22d3ee", "align": "center"},
            {"type": "text", "x": 0, "y": 500, "width": 800, "text": "原价 ¥1999", "fontSize": 20, "color": "#6b7280", "align": "center"},
            {"type": "rect", "x": 340, "y": 508, "width": 120, "height": 2, "fill": "#6b7280"},
            {"type": "text", "x": 0, "y": 540, "width": 800, "text": "预售价 ¥1799", "fontSize": 48, "fontWeight": "bold", "color": "#22d3ee", "align": "center"},
            {"type": "rect", "x": 300, "y": 650, "width": 200, "height": 64, "fill": "#22d3ee", "rx": 32},
            {"type": "text", "x": 300, "y": 670, "width": 200, "text": "立即预定", "fontSize": 22, "fontWeight": "bold", "color": "#111827", "align": "center"},
            {"type": "text", "x": 0, "y": 750, "width": 800, "text": "预售时间：即日起至月底", "fontSize": 16, "color": "#9ca3af", "align": "center"},
        ],
    },
    {
        "id": "tpl-social-digest",
        "name": "干货合集公众号封面",
        "category": "自媒体配图",
        "scene": "内容封面",
        "industry": "通用场景",
        "canvas_width": 900,
        "canvas_height": 500,
        "background": "#fef3c7",
        "thumbnail": thumb("social-digest", 300, 167),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 320, "height": 500, "fill": "#f59e0b"},
            {"type": "text", "x": 40, "y": 40, "width": 240, "text": "第 12 期", "fontSize": 18, "fontWeight": "bold", "color": "#fffbeb"},
            {"type": "text", "x": 40, "y": 170, "width": 240, "text": "12", "fontSize": 120, "fontWeight": "bold", "color": "#ffffff"},
            {"type": "text", "x": 360, "y": 160, "width": 500, "text": "干货合集", "fontSize": 48, "fontWeight": "bold", "color": "#78350f"},
            {"type": "text", "x": 360, "y": 250, "width": 480, "text": "5 个提升效率的实用技巧，收藏这一篇就够了", "fontSize": 20, "color": "#92400e"},
            {"type": "rect", "x": 360, "y": 320, "width": 140, "height": 40, "fill": "#78350f", "rx": 20},
            {"type": "text", "x": 360, "y": 332, "width": 140, "text": "职场干货", "fontSize": 16, "color": "#fef3c7", "align": "center"},
        ],
    },
    {
        "id": "tpl-handnews-recycle",
        "name": "垃圾分类环保手抄报",
        "category": "创意手作",
        "scene": "校园手抄报",
        "industry": "教育培训",
        "canvas_width": 700,
        "canvas_height": 900,
        "background": "#ecfdf5",
        "thumbnail": thumb("handnews-recycle", 300, 386),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 700, "height": 160, "fill": "#16a34a"},
            {"type": "text", "x": 0, "y": 55, "width": 700, "text": "垃圾分类 从我做起", "fontSize": 40, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 115, "width": 700, "text": "分类投放 · 变废为宝 · 守护家园", "fontSize": 18, "color": "#dcfce7", "align": "center"},
            {
                "type": "group",
                "x": 196,
                "y": 220,
                "children": [],
                "componentKind": "swot",
                "componentData": [
                    {"title": "可回收物", "body": "纸张、塑料瓶\n玻璃、金属", "color": "#3b82f6"},
                    {"title": "厨余垃圾", "body": "剩菜剩饭\n果皮菜叶", "color": "#22c55e"},
                    {"title": "有害垃圾", "body": "废电池\n过期药品", "color": "#ef4444"},
                    {"title": "其他垃圾", "body": "纸巾灰土\n受污染物品", "color": "#6b7280"},
                ],
            },
            {"type": "text", "x": 60, "y": 520, "width": 580, "text": "小小举动，大大改变——从今天开始，做分类小达人", "fontSize": 20, "fontWeight": "bold", "color": "#166534", "align": "center"},
            {"type": "rect", "x": 0, "y": 840, "width": 700, "height": 60, "fill": "#16a34a"},
            {"type": "text", "x": 0, "y": 860, "width": 700, "text": "班级：＿＿＿＿   姓名：＿＿＿＿", "fontSize": 16, "color": "#ffffff", "align": "center"},
        ],
    },
    {
        "id": "tpl-office-weekly",
        "name": "部门工作周报",
        "category": "职场文档",
        "scene": "通知公文",
        "industry": "企业办公",
        "canvas_width": 700,
        "canvas_height": 900,
        "background": "#ffffff",
        "thumbnail": thumb("office-weekly", 300, 386),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 700, "height": 110, "fill": "#1e40af"},
            {"type": "text", "x": 0, "y": 35, "width": 700, "text": "部门工作周报", "fontSize": 32, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 82, "width": 700, "text": "第＿＿周  ｜  汇报人：＿＿＿＿", "fontSize": 14, "color": "#bfdbfe", "align": "center"},
            {"type": "rect", "x": 40, "y": 150, "width": 6, "height": 24, "fill": "#1e40af"},
            {"type": "text", "x": 60, "y": 148, "width": 300, "text": "本周任务进度", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {
                "type": "group",
                "x": 60,
                "y": 195,
                "children": [],
                "componentKind": "bar-chart",
                "componentData": [
                    {"label": "需求评审", "value": 100, "color": "#8b5cf6"},
                    {"label": "开发联调", "value": 80, "color": "#38bdf8"},
                    {"label": "测试验收", "value": 60, "color": "#22c55e"},
                    {"label": "文档归档", "value": 40, "color": "#f59e0b"},
                ],
            },
            {"type": "rect", "x": 40, "y": 430, "width": 6, "height": 24, "fill": "#1e40af"},
            {"type": "text", "x": 60, "y": 428, "width": 300, "text": "本周工作总结", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 472, "width": 620, "text": "• 完成需求评审，明确了核心功能边界\n• 开发进度符合预期，联调阶段已启动\n• 测试用例覆盖率达到 80% 以上", "fontSize": 16, "color": "#374151"},
            {"type": "rect", "x": 40, "y": 620, "width": 6, "height": 24, "fill": "#1e40af"},
            {"type": "text", "x": 60, "y": 618, "width": 300, "text": "下周计划", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 662, "width": 620, "text": "• 完成剩余联调工作并提测\n• 补齐测试用例，推进验收\n• 输出功能文档并归档", "fontSize": 16, "color": "#374151"},
            {"type": "text", "x": 380, "y": 830, "width": 260, "text": "＿＿＿＿年＿＿月＿＿日", "fontSize": 14, "color": "#9ca3af", "align": "right"},
        ],
    },
    {
        "id": "tpl-handnews-coalgas",
        "name": "预防一氧化碳中毒手抄报",
        "category": "创意手作",
        "scene": "校园手抄报",
        "industry": "教育培训",
        "canvas_width": 700,
        "canvas_height": 900,
        "background": "#f0f9ff",
        "thumbnail": thumb("handnews-coalgas", 300, 386),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 700, "height": 150, "fill": "#0ea5e9"},
            {"type": "text", "x": 0, "y": 45, "width": 700, "text": "冬季取暖 预防中毒", "fontSize": 38, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 108, "width": 700, "text": "安全过冬 · 平安相伴", "fontSize": 18, "color": "#e0f2fe", "align": "center"},
            {"type": "rect", "x": 40, "y": 180, "width": 620, "height": 190, "fill": "#ffffff", "rx": 16},
            {"type": "text", "x": 68, "y": 204, "width": 560, "text": "什么是一氧化碳中毒", "fontSize": 20, "fontWeight": "bold", "color": "#0369a1"},
            {"type": "text", "x": 68, "y": 244, "width": 560, "text": "一氧化碳是无色无味的气体，煤炭、天然气等燃料燃烧不充分时产生。吸入后会出现头痛、头晕、恶心、四肢无力等症状，严重时可致命。", "fontSize": 16, "color": "#374151"},
            {"type": "rect", "x": 40, "y": 400, "width": 620, "height": 240, "fill": "#ffffff", "rx": 16},
            {"type": "text", "x": 68, "y": 424, "width": 560, "text": "预防措施", "fontSize": 20, "fontWeight": "bold", "color": "#0369a1"},
            {"type": "text", "x": 68, "y": 464, "width": 560, "text": "1. 室内使用煤气、木炭取暖时保持通风\n2. 定期检查燃气设备和排烟管道\n3. 不在密闭空间使用炭火取暖\n4. 安装一氧化碳报警器更安心\n5. 头晕恶心要立即开窗通风、离开现场", "fontSize": 16, "color": "#374151"},
            {"type": "rect", "x": 40, "y": 660, "width": 620, "height": 140, "fill": "#fef2f2", "rx": 16},
            {"type": "text", "x": 68, "y": 684, "width": 560, "text": "紧急处置", "fontSize": 20, "fontWeight": "bold", "color": "#dc2626"},
            {"type": "text", "x": 68, "y": 722, "width": 560, "text": "发现中毒者立即打开门窗，将人转移到空气新鲜处，拨打 120 急救电话。", "fontSize": 16, "color": "#374151"},
            {"type": "text", "x": 0, "y": 840, "width": 700, "text": "班级：＿＿＿＿   姓名：＿＿＿＿", "fontSize": 16, "color": "#0369a1", "align": "center"},
        ],
    },
    {
        "id": "tpl-print-supermarket-flyer",
        "name": "超市促销宣传单",
        "category": "印刷制品",
        "scene": "门店物料",
        "industry": "电商零售",
        "canvas_width": 700,
        "canvas_height": 900,
        "background": "#e0f2fe",
        "thumbnail": thumb("print-supermarket-flyer", 300, 386),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 700, "height": 140, "fill": "#0284c7"},
            {"type": "text", "x": 40, "y": 30, "width": 400, "text": "惠民生活超市", "fontSize": 26, "fontWeight": "bold", "color": "#ffffff"},
            {"type": "text", "x": 40, "y": 72, "width": 400, "text": "10.20 - 10.24 全场特惠", "fontSize": 16, "color": "#e0f2fe"},
            {"type": "text", "x": 0, "y": 170, "width": 700, "text": "惊喜好价 天天优惠", "fontSize": 32, "fontWeight": "bold", "color": "#0c4a6e", "align": "center"},
            {"type": "rect", "x": 50, "y": 260, "width": 300, "height": 110, "fill": "#ffffff", "rx": 10},
            {"type": "text", "x": 70, "y": 276, "width": 260, "text": "新鲜苹果", "fontSize": 17, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "rect", "x": 70, "y": 316, "width": 100, "height": 36, "fill": "#f97316", "rx": 6},
            {"type": "text", "x": 70, "y": 324, "width": 100, "text": "¥6.9", "fontSize": 18, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "rect", "x": 370, "y": 260, "width": 300, "height": 110, "fill": "#ffffff", "rx": 10},
            {"type": "text", "x": 390, "y": 276, "width": 260, "text": "优质大米", "fontSize": 17, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "rect", "x": 390, "y": 316, "width": 100, "height": 36, "fill": "#f97316", "rx": 6},
            {"type": "text", "x": 390, "y": 324, "width": 100, "text": "¥39.9", "fontSize": 18, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "rect", "x": 50, "y": 390, "width": 300, "height": 110, "fill": "#ffffff", "rx": 10},
            {"type": "text", "x": 70, "y": 406, "width": 260, "text": "精选牛肉", "fontSize": 17, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "rect", "x": 70, "y": 446, "width": 100, "height": 36, "fill": "#f97316", "rx": 6},
            {"type": "text", "x": 70, "y": 454, "width": 100, "text": "¥45", "fontSize": 18, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "rect", "x": 370, "y": 390, "width": 300, "height": 110, "fill": "#ffffff", "rx": 10},
            {"type": "text", "x": 390, "y": 406, "width": 260, "text": "儿童牛奶", "fontSize": 17, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "rect", "x": 390, "y": 446, "width": 100, "height": 36, "fill": "#f97316", "rx": 6},
            {"type": "text", "x": 390, "y": 454, "width": 100, "text": "¥28", "fontSize": 18, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "rect", "x": 50, "y": 520, "width": 300, "height": 110, "fill": "#ffffff", "rx": 10},
            {"type": "text", "x": 70, "y": 536, "width": 260, "text": "厨房纸巾", "fontSize": 17, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "rect", "x": 70, "y": 576, "width": 100, "height": 36, "fill": "#f97316", "rx": 6},
            {"type": "text", "x": 70, "y": 584, "width": 100, "text": "¥15.9", "fontSize": 18, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "rect", "x": 370, "y": 520, "width": 300, "height": 110, "fill": "#ffffff", "rx": 10},
            {"type": "text", "x": 390, "y": 536, "width": 260, "text": "洗洁精", "fontSize": 17, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "rect", "x": 390, "y": 576, "width": 100, "height": 36, "fill": "#f97316", "rx": 6},
            {"type": "text", "x": 390, "y": 584, "width": 100, "text": "¥9.9", "fontSize": 18, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "rect", "x": 0, "y": 800, "width": 700, "height": 100, "fill": "#0284c7"},
            {"type": "text", "x": 0, "y": 830, "width": 700, "text": "地址：XX市XX路惠民超市  电话：XXX-XXXXXXX", "fontSize": 14, "color": "#ffffff", "align": "center"},
        ],
    },
    {
        "id": "tpl-board-party-building",
        "name": "党建主题宣传展板",
        "category": "广告设计",
        "scene": "宣传展板",
        "industry": "企业办公",
        "canvas_width": 1000,
        "canvas_height": 1000,
        "background": "#c1272d",
        "thumbnail": "/templates/party-building-bg.png",
        "elements": [
            {"type": "image", "x": 0, "y": 0, "width": 1000, "height": 1000, "src": "/templates/party-building-bg.png"},
            {"type": "text", "x": 100, "y": 260, "width": 800, "text": "喜迎华诞 礼赞盛世", "fontSize": 62, "fontWeight": "bold", "color": "#fde047", "align": "center"},
            {"type": "text", "x": 100, "y": 370, "width": 800, "text": "党建引领 · 凝心聚力 · 共谱新篇", "fontSize": 26, "color": "#fef3c7", "align": "center"},
        ],
    },
]


def seed_if_empty(db: Session):
    if db.query(models.Template).count() > 0:
        backfill_scene_industry(db)
        add_missing_official_templates(db)
        return
    for data in SEED_TEMPLATES:
        db.add(models.Template(is_official=1, **data))
    db.commit()


def add_missing_official_templates(db: Session):
    """老部署已经跑过 seed_if_empty 的一次性插入，之后在 SEED_TEMPLATES 里新加的官方模板
    要靠这个按 id 补插，不会重复插入也不会动到已有数据"""
    existing_ids = {row.id for row in db.query(models.Template.id).filter(models.Template.is_official == 1)}
    added = False
    for data in SEED_TEMPLATES:
        if data["id"] not in existing_ids:
            db.add(models.Template(is_official=1, **data))
            added = True
    if added:
        db.commit()


def backfill_scene_industry(db: Session):
    """老部署的官方模板行是在 scene/industry 列加进来之前建的，migrate_schema 只能填统一默认值，
    这里按 id 对上 SEED_TEMPLATES 把每条模板具体的 scene/industry 补齐"""
    by_id = {t["id"]: t for t in SEED_TEMPLATES}
    changed = False
    for row in db.query(models.Template).filter(models.Template.is_official == 1):
        seed = by_id.get(row.id)
        if not seed:
            continue
        if row.scene != seed["scene"] or row.industry != seed["industry"]:
            row.scene = seed["scene"]
            row.industry = seed["industry"]
            changed = True
    if changed:
        db.commit()
