from sqlalchemy.orm import Session

from app import models


def thumb(seed: str, w: int = 300, h: int = 400) -> str:
    return f"https://picsum.photos/seed/{seed}/{w}/{h}"


SEED_TEMPLATES = [
    {
        "id": "tpl-poster-sale",
        "name": "促销海报",
        "category": "广告设计",
        "scene": "促销活动",
        "industry": "电商零售",
        "canvas_width": 600,
        "canvas_height": 800,
        "background": "#fef3c7",
        "thumbnail": thumb("sale-poster"),
        "elements": [
            {"type": "image", "x": 0, "y": 0, "width": 600, "height": 400, "src": thumb("sale-poster-bg", 600, 400)},
            {"type": "text", "x": 40, "y": 430, "width": 520, "text": "全场大促", "fontSize": 56, "fontWeight": "bold", "color": "#dc2626", "align": "center"},
            {"type": "text", "x": 40, "y": 510, "width": 520, "text": "低至 3 折起", "fontSize": 28, "color": "#78350f", "align": "center"},
            {"type": "rect", "x": 200, "y": 600, "width": 200, "height": 56, "fill": "#dc2626", "rx": 28},
            {"type": "text", "x": 200, "y": 616, "width": 200, "text": "立即抢购", "fontSize": 22, "color": "#ffffff", "align": "center"},
        ],
    },
    {
        "id": "tpl-flyer-open",
        "name": "开业宣传单",
        "category": "宣传海报",
        "scene": "开业宣传",
        "industry": "餐饮美食",
        "canvas_width": 600,
        "canvas_height": 800,
        "background": "#dbeafe",
        "thumbnail": thumb("open-flyer"),
        "elements": [
            {"type": "text", "x": 40, "y": 60, "width": 520, "text": "盛大开业", "fontSize": 48, "fontWeight": "bold", "color": "#1d4ed8", "align": "center"},
            {"type": "image", "x": 60, "y": 160, "width": 480, "height": 360, "src": thumb("open-flyer-bg", 480, 360)},
            {"type": "text", "x": 40, "y": 560, "width": 520, "text": "开业期间全场 8 折", "fontSize": 26, "color": "#1e3a8a", "align": "center"},
            {"type": "text", "x": 40, "y": 700, "width": 520, "text": "地址：XX市XX路XX号", "fontSize": 18, "color": "#374151", "align": "center"},
        ],
    },
    {
        "id": "tpl-print-menu",
        "name": "菜单印刷",
        "category": "印刷制品",
        "scene": "门店物料",
        "industry": "餐饮美食",
        "canvas_width": 600,
        "canvas_height": 800,
        "background": "#fff7ed",
        "thumbnail": thumb("menu-print"),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 600, "height": 120, "fill": "#ea580c"},
            {"type": "text", "x": 40, "y": 40, "width": 520, "text": "菜单", "fontSize": 40, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 60, "y": 160, "width": 480, "text": "招牌菜品 A ........ 38", "fontSize": 20, "color": "#374151"},
            {"type": "text", "x": 60, "y": 210, "width": 480, "text": "招牌菜品 B ........ 28", "fontSize": 20, "color": "#374151"},
            {"type": "text", "x": 60, "y": 260, "width": 480, "text": "招牌菜品 C ........ 18", "fontSize": 20, "color": "#374151"},
            {"type": "image", "x": 60, "y": 340, "width": 480, "height": 300, "src": thumb("menu-print-bg", 480, 300)},
        ],
    },
    {
        "id": "tpl-ecom-banner",
        "name": "电商主图",
        "category": "电商营销",
        "scene": "促销活动",
        "industry": "电商零售",
        "canvas_width": 800,
        "canvas_height": 800,
        "background": "#f0fdf4",
        "thumbnail": thumb("ecom-banner", 300, 300),
        "elements": [
            {"type": "image", "x": 0, "y": 0, "width": 800, "height": 800, "src": thumb("ecom-banner-bg", 800, 800)},
            {"type": "rect", "x": 40, "y": 40, "width": 260, "height": 80, "fill": "#16a34a", "rx": 16},
            {"type": "text", "x": 40, "y": 62, "width": 260, "text": "新品上市", "fontSize": 28, "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 40, "y": 680, "width": 720, "text": "限时特惠 ¥99", "fontSize": 44, "fontWeight": "bold", "color": "#166534", "align": "center"},
        ],
    },
    {
        "id": "tpl-social-post",
        "name": "公众号封面",
        "category": "自媒体配图",
        "scene": "内容封面",
        "industry": "通用场景",
        "canvas_width": 900,
        "canvas_height": 500,
        "background": "#ede9fe",
        "thumbnail": thumb("social-post", 300, 167),
        "elements": [
            {"type": "image", "x": 0, "y": 0, "width": 900, "height": 500, "src": thumb("social-post-bg", 900, 500)},
            {"type": "rect", "x": 0, "y": 380, "width": 900, "height": 120, "fill": "rgba(0,0,0,0.45)"},
            {"type": "text", "x": 40, "y": 410, "width": 820, "text": "在这里输入你的标题", "fontSize": 36, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
        ],
    },
    {
        "id": "tpl-card-thankyou",
        "name": "感谢卡",
        "category": "宣传海报",
        "scene": "感恩贺卡",
        "industry": "通用场景",
        "canvas_width": 600,
        "canvas_height": 800,
        "background": "#fce7f3",
        "thumbnail": thumb("thankyou-card"),
        "elements": [
            {"type": "text", "x": 40, "y": 80, "width": 520, "text": "Thank You", "fontSize": 44, "fontWeight": "bold", "color": "#be185d", "align": "center"},
            {"type": "image", "x": 100, "y": 200, "width": 400, "height": 400, "src": thumb("thankyou-card-bg", 400, 400)},
            {"type": "text", "x": 40, "y": 640, "width": 520, "text": "感谢一路有你", "fontSize": 24, "color": "#831843", "align": "center"},
        ],
    },
    {
        "id": "tpl-handnews-traffic",
        "name": "交通安全手抄报",
        "category": "创意手作",
        "scene": "校园手抄报",
        "industry": "教育培训",
        "canvas_width": 700,
        "canvas_height": 900,
        "background": "#dbeafe",
        "thumbnail": thumb("handnews-traffic", 300, 386),
        "elements": [
            {"type": "image", "x": 0, "y": 0, "width": 700, "height": 380, "src": thumb("handnews-traffic-bg", 700, 380)},
            {"type": "text", "x": 40, "y": 400, "width": 620, "text": "交通安全", "fontSize": 64, "fontWeight": "bold", "color": "#dc2626", "align": "center"},
            {"type": "rect", "x": 40, "y": 500, "width": 290, "height": 350, "fill": "#ffffff", "rx": 20},
            {"type": "rect", "x": 370, "y": 500, "width": 290, "height": 350, "fill": "#ffffff", "rx": 20},
            {"type": "text", "x": 60, "y": 530, "width": 250, "text": "1.要走人行道，没\n有人行道时靠边\n走。\n2.结伴外出时，不\n打闹嬉戏。\n3.过马路时不看手\n机，注意观察车辆", "fontSize": 20, "color": "#1f2937"},
            {"type": "text", "x": 390, "y": 530, "width": 250, "text": "骑车出行要戴头\n盔，不可载人，\n出行前检查车\n辆，不逆行，应\n走非机动车道", "fontSize": 20, "color": "#1f2937"},
        ],
    },
    {
        "id": "tpl-handnews-reading",
        "name": "读书手抄报",
        "category": "创意手作",
        "scene": "校园手抄报",
        "industry": "教育培训",
        "canvas_width": 700,
        "canvas_height": 900,
        "background": "#fef9e7",
        "thumbnail": thumb("handnews-reading", 300, 386),
        "elements": [
            {"type": "image", "x": 60, "y": 40, "width": 580, "height": 320, "src": thumb("handnews-reading-bg", 580, 320)},
            {"type": "text", "x": 40, "y": 380, "width": 620, "text": "好书伴我成长", "fontSize": 56, "fontWeight": "bold", "color": "#b45309", "align": "center"},
            {"type": "rect", "x": 40, "y": 470, "width": 620, "height": 180, "fill": "#ffffff", "rx": 20},
            {"type": "text", "x": 70, "y": 500, "width": 560, "text": "推荐理由：这本书教会我遇到困难\n不放弃，主人公勇敢善良的品质\n很值得我们学习。", "fontSize": 22, "color": "#374151"},
            {"type": "rect", "x": 40, "y": 680, "width": 620, "height": 180, "fill": "#ffffff", "rx": 20},
            {"type": "text", "x": 70, "y": 710, "width": 560, "text": "读后感：读完这本书，我明白了坚\n持的意义，以后我也要做一个不\n轻言放弃的人。", "fontSize": 22, "color": "#374151"},
        ],
    },
    {
        "id": "tpl-office-resume",
        "name": "个人简历",
        "category": "职场文档",
        "scene": "简历文档",
        "industry": "企业办公",
        "canvas_width": 700,
        "canvas_height": 950,
        "background": "#ffffff",
        "thumbnail": thumb("office-resume", 300, 407),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 700, "height": 150, "fill": "#1f2937"},
            {"type": "text", "x": 40, "y": 30, "width": 500, "text": "张三", "fontSize": 36, "fontWeight": "bold", "color": "#ffffff"},
            {"type": "text", "x": 40, "y": 86, "width": 500, "text": "求职意向：前端开发工程师", "fontSize": 18, "color": "#dbeafe"},
            {"type": "text", "x": 40, "y": 118, "width": 600, "text": "138-0000-0000  |  zhangsan@email.com  |  北京", "fontSize": 14, "color": "#9ca3af"},
            {"type": "rect", "x": 40, "y": 190, "width": 6, "height": 24, "fill": "#2563eb"},
            {"type": "text", "x": 60, "y": 188, "width": 300, "text": "教育经历", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 232, "width": 500, "text": "北京大学  ·  计算机科学与技术  ·  本科", "fontSize": 16, "color": "#374151"},
            {"type": "text", "x": 40, "y": 258, "width": 500, "text": "2018.09 - 2022.06", "fontSize": 14, "color": "#9ca3af"},
            {"type": "rect", "x": 40, "y": 310, "width": 6, "height": 24, "fill": "#2563eb"},
            {"type": "text", "x": 60, "y": 308, "width": 300, "text": "工作经历", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 352, "width": 500, "text": "某某科技有限公司  ·  前端开发工程师", "fontSize": 16, "color": "#374151"},
            {"type": "text", "x": 40, "y": 378, "width": 500, "text": "2022.07 - 至今", "fontSize": 14, "color": "#9ca3af"},
            {"type": "text", "x": 40, "y": 408, "width": 620, "text": "• 负责公司核心产品的前端架构设计与开发\n• 主导性能优化专项，首屏加载速度提升 40%\n• 带领 3 人小组完成组件库建设，提升团队协作效率", "fontSize": 16, "color": "#374151"},
            {"type": "rect", "x": 40, "y": 540, "width": 6, "height": 24, "fill": "#2563eb"},
            {"type": "text", "x": 60, "y": 538, "width": 300, "text": "技能特长", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 582, "width": 620, "text": "• 熟练掌握 Vue3 / React / TypeScript\n• 熟悉前端工程化、性能优化与自动化测试\n• 良好的沟通表达与团队协作能力", "fontSize": 16, "color": "#374151"},
            {"type": "rect", "x": 40, "y": 712, "width": 6, "height": 24, "fill": "#2563eb"},
            {"type": "text", "x": 60, "y": 710, "width": 300, "text": "自我评价", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 754, "width": 620, "text": "工作认真负责，学习能力强，能够快速适应新\n技术栈，具备良好的问题排查与解决能力。", "fontSize": 16, "color": "#374151"},
        ],
    },
    {
        "id": "tpl-office-resume-sidebar",
        "name": "简历（双栏）",
        "category": "职场文档",
        "scene": "简历文档",
        "industry": "企业办公",
        "canvas_width": 700,
        "canvas_height": 950,
        "background": "#ffffff",
        "thumbnail": thumb("office-resume-sidebar", 300, 407),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 220, "height": 950, "fill": "#1e3a5f"},
            {"type": "rect", "x": 55, "y": 50, "width": 110, "height": 110, "fill": "#33547a", "rx": 55},
            {"type": "text", "x": 0, "y": 180, "width": 220, "text": "李 娜", "fontSize": 26, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 215, "width": 220, "text": "视觉设计师", "fontSize": 14, "color": "#a8c5e0", "align": "center"},
            {"type": "rect", "x": 40, "y": 250, "width": 140, "height": 2, "fill": "#5b9bd5"},
            {"type": "text", "x": 30, "y": 275, "width": 160, "text": "联系方式", "fontSize": 14, "fontWeight": "bold", "color": "#ffffff"},
            {"type": "text", "x": 30, "y": 302, "width": 170, "text": "电话：138-0000-0000\n邮箱：lina@email.com\n城市：广州\n微信：liwei_design", "fontSize": 12, "color": "#c7d6e8"},
            {"type": "text", "x": 30, "y": 400, "width": 160, "text": "专业技能", "fontSize": 14, "fontWeight": "bold", "color": "#ffffff"},
            {"type": "text", "x": 30, "y": 430, "width": 160, "text": "UI 设计", "fontSize": 11, "color": "#dbe7f5"},
            {"type": "rect", "x": 30, "y": 448, "width": 160, "height": 6, "fill": "#33547a", "rx": 3},
            {"type": "rect", "x": 30, "y": 448, "width": 144, "height": 6, "fill": "#5b9bd5", "rx": 3},
            {"type": "text", "x": 30, "y": 476, "width": 160, "text": "品牌视觉", "fontSize": 11, "color": "#dbe7f5"},
            {"type": "rect", "x": 30, "y": 494, "width": 160, "height": 6, "fill": "#33547a", "rx": 3},
            {"type": "rect", "x": 30, "y": 494, "width": 128, "height": 6, "fill": "#5b9bd5", "rx": 3},
            {"type": "text", "x": 30, "y": 522, "width": 160, "text": "摄影修图", "fontSize": 11, "color": "#dbe7f5"},
            {"type": "rect", "x": 30, "y": 540, "width": 160, "height": 6, "fill": "#33547a", "rx": 3},
            {"type": "rect", "x": 30, "y": 540, "width": 120, "height": 6, "fill": "#5b9bd5", "rx": 3},
            {"type": "text", "x": 30, "y": 568, "width": 160, "text": "Figma / AI / PS", "fontSize": 11, "color": "#dbe7f5"},
            {"type": "rect", "x": 30, "y": 586, "width": 160, "height": 6, "fill": "#33547a", "rx": 3},
            {"type": "rect", "x": 30, "y": 586, "width": 136, "height": 6, "fill": "#5b9bd5", "rx": 3},
            {"type": "text", "x": 30, "y": 630, "width": 160, "text": "语言能力", "fontSize": 14, "fontWeight": "bold", "color": "#ffffff"},
            {"type": "text", "x": 30, "y": 657, "width": 170, "text": "中文（母语）\n英语（CET-6，流利）", "fontSize": 12, "color": "#c7d6e8"},
            {"type": "text", "x": 250, "y": 50, "width": 300, "text": "工作经历", "fontSize": 20, "fontWeight": "bold", "color": "#1e3a5f"},
            {"type": "rect", "x": 250, "y": 84, "width": 40, "height": 3, "fill": "#5b9bd5"},
            {"type": "text", "x": 250, "y": 102, "width": 410, "text": "资深视觉设计师 · 某某科技有限公司", "fontSize": 15, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 250, "y": 124, "width": 410, "text": "2021.03 - 至今", "fontSize": 12, "color": "#9ca3af"},
            {"type": "text", "x": 250, "y": 148, "width": 420, "text": "• 负责公司品牌视觉体系搭建与迭代\n• 主导 App 界面改版，用户满意度提升 25%\n• 指导初级设计师，把控团队设计质量", "fontSize": 13, "color": "#374151"},
            {"type": "text", "x": 250, "y": 225, "width": 410, "text": "视觉设计师 · 某某广告有限公司", "fontSize": 15, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 250, "y": 247, "width": 410, "text": "2019.07 - 2021.02", "fontSize": 12, "color": "#9ca3af"},
            {"type": "text", "x": 250, "y": 271, "width": 420, "text": "• 独立完成多个品牌客户的视觉设计项目\n• 协助制定设计规范手册，提升团队交付效率", "fontSize": 13, "color": "#374151"},
            {"type": "text", "x": 250, "y": 345, "width": 300, "text": "教育背景", "fontSize": 20, "fontWeight": "bold", "color": "#1e3a5f"},
            {"type": "rect", "x": 250, "y": 379, "width": 40, "height": 3, "fill": "#5b9bd5"},
            {"type": "text", "x": 250, "y": 397, "width": 410, "text": "广州美术学院 · 视觉传达设计 · 本科", "fontSize": 15, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 250, "y": 419, "width": 410, "text": "2015.09 - 2019.06", "fontSize": 12, "color": "#9ca3af"},
            {"type": "text", "x": 250, "y": 460, "width": 300, "text": "项目经验", "fontSize": 20, "fontWeight": "bold", "color": "#1e3a5f"},
            {"type": "rect", "x": 250, "y": 494, "width": 40, "height": 3, "fill": "#5b9bd5"},
            {"type": "text", "x": 250, "y": 512, "width": 410, "text": "XX品牌视觉升级项目 · 项目主创", "fontSize": 15, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 250, "y": 536, "width": 420, "text": "• 独立完成品牌LOGO及VI系统设计\n• 协同市场部完成三场大型campaign视觉物料", "fontSize": 13, "color": "#374151"},
            {"type": "text", "x": 250, "y": 610, "width": 300, "text": "获奖荣誉", "fontSize": 20, "fontWeight": "bold", "color": "#1e3a5f"},
            {"type": "rect", "x": 250, "y": 644, "width": 40, "height": 3, "fill": "#5b9bd5"},
            {"type": "text", "x": 250, "y": 662, "width": 420, "text": "• 2023年度公司优秀员工\n• 第八届学院奖视觉设计类银奖", "fontSize": 13, "color": "#374151"},
        ],
    },
    {
        "id": "tpl-office-resume-fresh",
        "name": "简历（应届生）",
        "category": "职场文档",
        "scene": "简历文档",
        "industry": "通用场景",
        "canvas_width": 700,
        "canvas_height": 950,
        "background": "#ffffff",
        "thumbnail": thumb("office-resume-fresh", 300, 407),
        "elements": [
            {"type": "text", "x": 40, "y": 50, "width": 500, "text": "王 悦", "fontSize": 34, "fontWeight": "bold", "color": "#0f766e"},
            {"type": "text", "x": 40, "y": 95, "width": 500, "text": "应届毕业生 · 市场营销专业", "fontSize": 16, "color": "#374151"},
            {"type": "text", "x": 40, "y": 125, "width": 620, "text": "138-0000-0000  |  wangyue@email.com  |  杭州  |  可立即到岗", "fontSize": 13, "color": "#6b7280"},
            {"type": "rect", "x": 40, "y": 158, "width": 620, "height": 2, "fill": "#99f6e4"},
            {"type": "rect", "x": 40, "y": 186, "width": 4, "height": 20, "fill": "#14b8a6"},
            {"type": "text", "x": 54, "y": 185, "width": 300, "text": "教育背景", "fontSize": 19, "fontWeight": "bold", "color": "#0f766e"},
            {"type": "text", "x": 40, "y": 222, "width": 620, "text": "杭州师范大学 · 市场营销 · 本科（2020.09-2024.06）", "fontSize": 15, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 248, "width": 620, "text": "主修课程：市场调研、消费者行为学、品牌管理；绩点 3.7/4.0，专业排名前 10%", "fontSize": 13, "color": "#6b7280"},
            {"type": "rect", "x": 40, "y": 306, "width": 4, "height": 20, "fill": "#14b8a6"},
            {"type": "text", "x": 54, "y": 305, "width": 300, "text": "实习经历", "fontSize": 19, "fontWeight": "bold", "color": "#0f766e"},
            {"type": "text", "x": 40, "y": 340, "width": 620, "text": "某某快消品公司 · 市场部实习生（2023.06-2023.09）", "fontSize": 15, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 365, "width": 620, "text": "• 协助策划社交媒体 campaign，参与内容超 20 篇，累计曝光 50万+\n• 整理竞品调研报告，为季度营销策略提供数据支持", "fontSize": 13, "color": "#374151"},
            {"type": "text", "x": 40, "y": 425, "width": 620, "text": "某某互联网公司 · 品牌实习生（2022.12-2023.03）", "fontSize": 15, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 450, "width": 620, "text": "• 参与品牌线下活动执行，负责物料对接与现场协调", "fontSize": 13, "color": "#374151"},
            {"type": "rect", "x": 40, "y": 505, "width": 4, "height": 20, "fill": "#14b8a6"},
            {"type": "text", "x": 54, "y": 504, "width": 300, "text": "项目经验", "fontSize": 19, "fontWeight": "bold", "color": "#0f766e"},
            {"type": "text", "x": 40, "y": 540, "width": 620, "text": "校园品牌推广大赛 · 团队负责人", "fontSize": 15, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 565, "width": 620, "text": "• 带领 5 人团队完成校园品牌传播方案，获校级二等奖", "fontSize": 13, "color": "#374151"},
            {"type": "rect", "x": 40, "y": 615, "width": 4, "height": 20, "fill": "#14b8a6"},
            {"type": "text", "x": 54, "y": 614, "width": 300, "text": "技能证书", "fontSize": 19, "fontWeight": "bold", "color": "#0f766e"},
            {"type": "rect", "x": 40, "y": 650, "width": 112, "height": 34, "fill": "#ccfbf1", "rx": 17},
            {"type": "text", "x": 40, "y": 659, "width": 112, "text": "新媒体运营", "fontSize": 13, "color": "#0f766e", "align": "center"},
            {"type": "rect", "x": 162, "y": 650, "width": 96, "height": 34, "fill": "#ccfbf1", "rx": 17},
            {"type": "text", "x": 162, "y": 659, "width": 96, "text": "数据分析", "fontSize": 13, "color": "#0f766e", "align": "center"},
            {"type": "rect", "x": 268, "y": 650, "width": 110, "height": 34, "fill": "#ccfbf1", "rx": 17},
            {"type": "text", "x": 268, "y": 659, "width": 110, "text": "PPT / Excel", "fontSize": 13, "color": "#0f766e", "align": "center"},
            {"type": "rect", "x": 388, "y": 650, "width": 110, "height": 34, "fill": "#ccfbf1", "rx": 17},
            {"type": "text", "x": 388, "y": 659, "width": 110, "text": "英语 CET-6", "fontSize": 13, "color": "#0f766e", "align": "center"},
            {"type": "rect", "x": 508, "y": 650, "width": 104, "height": 34, "fill": "#ccfbf1", "rx": 17},
            {"type": "text", "x": 508, "y": 659, "width": 104, "text": "Photoshop", "fontSize": 13, "color": "#0f766e", "align": "center"},
            {"type": "rect", "x": 40, "y": 705, "width": 4, "height": 20, "fill": "#14b8a6"},
            {"type": "text", "x": 54, "y": 704, "width": 300, "text": "自我评价", "fontSize": 19, "fontWeight": "bold", "color": "#0f766e"},
            {"type": "text", "x": 40, "y": 740, "width": 620, "text": "性格开朗，学习能力强，具备良好的团队协作精神与责任心；对新媒体营销和品牌传播有浓厚兴趣，善于从数据中发现问题并提出解决方案。", "fontSize": 13, "color": "#374151"},
            {"type": "rect", "x": 0, "y": 930, "width": 700, "height": 20, "fill": "#14b8a6"},
        ],
    },
    {
        "id": "tpl-office-leave",
        "name": "请假条",
        "category": "职场文档",
        "scene": "通知公文",
        "industry": "企业办公",
        "canvas_width": 700,
        "canvas_height": 700,
        "background": "#ffffff",
        "thumbnail": thumb("office-leave", 300, 300),
        "elements": [
            {"type": "text", "x": 40, "y": 50, "width": 620, "text": "请假条", "fontSize": 40, "fontWeight": "bold", "color": "#1f2937", "align": "center"},
            {"type": "rect", "x": 260, "y": 112, "width": 180, "height": 3, "fill": "#9ca3af"},
            {"type": "text", "x": 60, "y": 170, "width": 580, "text": "尊敬的领导：", "fontSize": 18, "color": "#374151"},
            {"type": "text", "x": 60, "y": 216, "width": 580, "text": "本人因＿＿＿＿＿＿＿＿＿＿＿＿＿＿事由，\n需请假＿＿天，自＿＿＿＿年＿＿月＿＿日起，\n至＿＿＿＿年＿＿月＿＿日止，请予批准。", "fontSize": 18, "color": "#374151"},
            {"type": "text", "x": 60, "y": 360, "width": 580, "text": "特此申请，谢谢！", "fontSize": 18, "color": "#374151"},
            {"type": "text", "x": 60, "y": 560, "width": 400, "text": "申请人：＿＿＿＿＿＿", "fontSize": 18, "color": "#1f2937"},
            {"type": "text", "x": 60, "y": 604, "width": 400, "text": "日 期：＿＿＿＿年＿＿月＿＿日", "fontSize": 18, "color": "#1f2937"},
            {"type": "text", "x": 380, "y": 560, "width": 280, "text": "部门负责人：＿＿＿＿＿＿", "fontSize": 18, "color": "#1f2937"},
        ],
    },
    {
        "id": "tpl-office-meeting",
        "name": "会议通知",
        "category": "职场文档",
        "scene": "通知公文",
        "industry": "企业办公",
        "canvas_width": 700,
        "canvas_height": 780,
        "background": "#ffffff",
        "thumbnail": thumb("office-meeting", 300, 334),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 700, "height": 96, "fill": "#0f766e"},
            {"type": "text", "x": 40, "y": 30, "width": 620, "text": "会议通知", "fontSize": 32, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 60, "y": 136, "width": 580, "text": "各部门负责人：\n兹定于近期召开月度工作总结会议，请相关\n人员准时参加，具体安排如下：", "fontSize": 18, "color": "#1f2937"},
            {"type": "rect", "x": 60, "y": 260, "width": 580, "height": 220, "fill": "#f0fdfa", "rx": 12},
            {"type": "text", "x": 90, "y": 288, "width": 520, "text": "时间：＿＿＿＿年＿＿月＿＿日 ＿＿:＿＿", "fontSize": 18, "color": "#0f766e", "fontWeight": "bold"},
            {"type": "text", "x": 90, "y": 328, "width": 520, "text": "地点：公司三楼会议室", "fontSize": 18, "color": "#0f766e", "fontWeight": "bold"},
            {"type": "text", "x": 90, "y": 368, "width": 520, "text": "参会人员：各部门负责人", "fontSize": 18, "color": "#0f766e", "fontWeight": "bold"},
            {"type": "text", "x": 90, "y": 408, "width": 520, "text": "会议主题：月度工作总结", "fontSize": 18, "color": "#0f766e", "fontWeight": "bold"},
            {"type": "text", "x": 60, "y": 520, "width": 580, "text": "请与会人员提前做好相关准备工作，如有特殊\n情况无法参加，请提前向行政部请假。", "fontSize": 16, "color": "#374151"},
            {"type": "text", "x": 300, "y": 660, "width": 340, "text": "XX 公司行政部", "fontSize": 16, "color": "#1f2937", "align": "right"},
            {"type": "text", "x": 300, "y": 690, "width": 340, "text": "＿＿＿＿年＿＿月＿＿日", "fontSize": 16, "color": "#1f2937", "align": "right"},
        ],
    },
    {
        "id": "tpl-office-invitation",
        "name": "邀请函",
        "category": "职场文档",
        "scene": "邀请函卡",
        "industry": "企业办公",
        "canvas_width": 700,
        "canvas_height": 900,
        "background": "#1e293b",
        "thumbnail": thumb("office-invitation", 300, 386),
        "elements": [
            {"type": "rect", "x": 30, "y": 30, "width": 640, "height": 4, "fill": "#d4af37"},
            {"type": "rect", "x": 30, "y": 866, "width": 640, "height": 4, "fill": "#d4af37"},
            {"type": "rect", "x": 30, "y": 30, "width": 4, "height": 840, "fill": "#d4af37"},
            {"type": "rect", "x": 666, "y": 30, "width": 4, "height": 840, "fill": "#d4af37"},
            {"type": "text", "x": 40, "y": 130, "width": 620, "text": "邀 请 函", "fontSize": 46, "fontWeight": "bold", "color": "#d4af37", "align": "center"},
            {"type": "text", "x": 40, "y": 196, "width": 620, "text": "I N V I T A T I O N", "fontSize": 14, "color": "#d4af37", "align": "center"},
            {"type": "text", "x": 70, "y": 320, "width": 560, "text": "尊敬的＿＿＿＿＿＿ 先生/女士：", "fontSize": 20, "color": "#e2e8f0"},
            {"type": "text", "x": 70, "y": 370, "width": 560, "text": "诚挚邀请您拨冗出席我们的年度盛典，\n期待您的莅临与支持，共襄盛举。", "fontSize": 18, "color": "#cbd5e1"},
            {"type": "rect", "x": 70, "y": 500, "width": 560, "height": 2, "fill": "#475569"},
            {"type": "text", "x": 70, "y": 540, "width": 560, "text": "时间：＿＿＿＿年＿＿月＿＿日 ＿＿:＿＿", "fontSize": 18, "color": "#e2e8f0"},
            {"type": "text", "x": 70, "y": 580, "width": 560, "text": "地点：＿＿＿＿＿＿＿＿＿＿＿＿＿＿", "fontSize": 18, "color": "#e2e8f0"},
            {"type": "text", "x": 70, "y": 620, "width": 560, "text": "主办方：＿＿＿＿＿＿＿＿＿＿＿＿", "fontSize": 18, "color": "#e2e8f0"},
            {"type": "text", "x": 70, "y": 780, "width": 560, "text": "敬请回复", "fontSize": 16, "color": "#94a3b8"},
        ],
    },
    {
        "id": "tpl-board-safety-month",
        "name": "安全生产月宣传展板",
        "category": "广告设计",
        "scene": "宣传展板",
        "industry": "企业办公",
        "canvas_width": 1200,
        "canvas_height": 970,
        "background": "#ffffff",
        "thumbnail": thumb("board-safety-month", 300, 242),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 1200, "height": 150, "fill": "#c1272d"},
            {"type": "text", "x": 0, "y": 32, "width": 1200, "text": "全国安全生产月", "fontSize": 52, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 100, "width": 1200, "text": "第25个全国「安全生产月」 · 2026年6月", "fontSize": 20, "color": "#fde8e8", "align": "center"},
            {"type": "rect", "x": 60, "y": 170, "width": 1080, "height": 70, "fill": "#fef3c7", "rx": 10},
            {"type": "text", "x": 60, "y": 190, "width": 1080, "text": "人人讲安全、个个会应急——排查整治风险隐患", "fontSize": 26, "fontWeight": "bold", "color": "#92400e", "align": "center"},
            {"type": "rect", "x": 60, "y": 270, "width": 530, "height": 190, "fill": "#f9fafb", "rx": 12},
            {"type": "text", "x": 88, "y": 296, "width": 474, "text": "消防安全 · 应急逃生", "fontSize": 23, "fontWeight": "bold", "color": "#dc2626"},
            {"type": "text", "x": 88, "y": 340, "width": 474, "text": "学习掌握火灾逃生、用电用气、电动自行车充电安全常识，清理占用疏散通道、堆放易燃物品等隐患，确保安全通道畅通无阻。", "fontSize": 17, "color": "#374151"},
            {"type": "rect", "x": 610, "y": 270, "width": 530, "height": 190, "fill": "#f9fafb", "rx": 12},
            {"type": "text", "x": 638, "y": 296, "width": 474, "text": "风险隐患排查整治", "fontSize": 23, "fontWeight": "bold", "color": "#ea580c"},
            {"type": "text", "x": 638, "y": 340, "width": 474, "text": "聚焦矿山、危险化学品、建筑施工、交通运输、工贸、燃气、消防等重点行业领域，全面排查整治各类安全风险隐患。", "fontSize": 17, "color": "#374151"},
            {"type": "rect", "x": 60, "y": 480, "width": 1080, "height": 190, "fill": "#f9fafb", "rx": 12},
            {"type": "rect", "x": 88, "y": 506, "width": 8, "height": 24, "fill": "#c1272d"},
            {"type": "text", "x": 104, "y": 504, "width": 200, "text": "五落实", "fontSize": 22, "fontWeight": "bold", "color": "#c1272d"},
            {"type": "text", "x": 88, "y": 546, "width": 474, "text": "1. 必须落实「党政同责」要求", "fontSize": 15, "color": "#374151"},
            {"type": "text", "x": 88, "y": 576, "width": 474, "text": "2. 必须落实安全生产「一岗双责」", "fontSize": 15, "color": "#374151"},
            {"type": "text", "x": 88, "y": 606, "width": 474, "text": "3. 必须落实安全生产组织领导机构", "fontSize": 15, "color": "#374151"},
            {"type": "text", "x": 88, "y": 636, "width": 474, "text": "4. 必须落实安全管理力量", "fontSize": 15, "color": "#374151"},
            {"type": "rect", "x": 638, "y": 506, "width": 8, "height": 24, "fill": "#2563eb"},
            {"type": "text", "x": 654, "y": 504, "width": 200, "text": "五到位", "fontSize": 22, "fontWeight": "bold", "color": "#2563eb"},
            {"type": "text", "x": 638, "y": 546, "width": 474, "text": "1. 安全责任到位  2. 安全投入到位", "fontSize": 15, "color": "#374151"},
            {"type": "text", "x": 638, "y": 576, "width": 474, "text": "3. 安全培训到位  4. 安全管理到位", "fontSize": 15, "color": "#374151"},
            {"type": "text", "x": 638, "y": 606, "width": 474, "text": "5. 应急救援到位", "fontSize": 15, "color": "#374151"},
            {"type": "text", "x": 638, "y": 636, "width": 474, "text": "五个方面同步到位，一处不落", "fontSize": 15, "color": "#9ca3af"},
            {"type": "rect", "x": 60, "y": 690, "width": 530, "height": 190, "fill": "#f9fafb", "rx": 12},
            {"type": "text", "x": 88, "y": 716, "width": 474, "text": "人人会应急", "fontSize": 23, "fontWeight": "bold", "color": "#2563eb"},
            {"type": "text", "x": 88, "y": 760, "width": 474, "text": "普及基本应急救护和避险技能，做到早发现、早报告、早处置，提升自救互救能力，筑牢身边的安全防线。", "fontSize": 17, "color": "#374151"},
            {"type": "rect", "x": 610, "y": 690, "width": 530, "height": 190, "fill": "#f9fafb", "rx": 12},
            {"type": "text", "x": 638, "y": 716, "width": 474, "text": "安全第一 入脑入心", "fontSize": 23, "fontWeight": "bold", "color": "#16a34a"},
            {"type": "text", "x": 638, "y": 760, "width": 474, "text": "每个人都是安全防线，每个岗位都是安全哨点。树牢安全发展理念，把安全生产责任落实到每一个岗位、每一个环节。", "fontSize": 17, "color": "#374151"},
            {"type": "text", "x": 0, "y": 910, "width": 1200, "text": "6 月 16 日 全国安全宣传咨询日", "fontSize": 18, "color": "#6b7280", "align": "center"},
            {"type": "text", "x": 700, "y": 940, "width": 440, "text": "＿＿＿＿＿＿＿＿ 单位  制", "fontSize": 16, "color": "#9ca3af", "align": "right"},
        ],
    },
    {
        "id": "tpl-board-safety-month-grid",
        "name": "安全生产月信息看板",
        "category": "广告设计",
        "scene": "宣传展板",
        "industry": "企业办公",
        "canvas_width": 2400,
        "canvas_height": 1285,
        "background": "#eef2f6",
        "thumbnail": thumb("board-safety-month-grid", 300, 161),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 2400, "height": 230, "fill": "#4a9fdb"},
            {"type": "rect", "x": 0, "y": 90, "width": 2400, "height": 150, "fill": "#8fd0f2"},
            {"type": "rect", "x": 0, "y": 190, "width": 2400, "height": 60, "fill": "#eaf6fd"},
            {"type": "group", "x": 0, "y": 0, "width": 2400, "height": 190, "children": [{"type": "circle", "x": 60, "y": 20, "radius": 34, "fill": "rgba(255,255,255,0.35)"}, {"type": "circle", "x": 140, "y": 55, "radius": 22, "fill": "rgba(255,255,255,0.28)"}, {"type": "circle", "x": 2280, "y": 15, "radius": 40, "fill": "rgba(255,255,255,0.30)"}, {"type": "circle", "x": 2180, "y": 60, "radius": 24, "fill": "rgba(255,255,255,0.24)"}]},
            {"type": "text", "x": 0, "y": 46, "width": 2400, "text": "2026年全国安全生产月主题活动", "fontSize": 54, "fontWeight": "bold", "color": "#c8161d", "align": "center", "stroke": "#f6c92e", "strokeWidth": 2, "shadowColor": "rgba(0,0,0,0.30)", "shadowBlur": 8, "shadowOffsetX": 2, "shadowOffsetY": 3},
            {"type": "text", "x": 0, "y": 128, "width": 2400, "text": "人人讲安全、个个会应急 —— 排查整治风险隐患", "fontSize": 22, "fontWeight": "bold", "color": "#a10f16", "align": "center"},
            {"type": "text", "x": 0, "y": 165, "width": 2400, "text": "第 25 个全国安全生产月 · 2026 年 6 月 · 6 月 16 日全国安全宣传咨询日（安徽合肥）", "fontSize": 15, "color": "#6b7280", "align": "center"},
            {"type": "group", "x": 60, "y": 212, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "2026年安全生产月宣传主题", "color": "#c8161d", "width": 432}]},
            {"type": "rect", "x": 60, "y": 254, "width": 432, "height": 40, "fill": "#fdeceb", "rx": 4},
            {"type": "text", "x": 72, "y": 264, "width": 408, "text": "人人讲安全、个个会应急——排查整治风险隐患", "fontSize": 14, "fontWeight": "bold", "color": "#a10f16"},
            {"type": "text", "x": 60, "y": 304, "width": 432, "text": "2026年6月是第25个全国“安全生产月”，主题为“人人讲安全、个个会应急——排查整治风险隐患”。活动固定在每年6月开展，6月16日为全国安全宣传咨询日。", "fontSize": 13, "color": "#374151"},
            {"type": "group", "x": 60, "y": 381, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "什么是安全生产月", "color": "#c8161d", "width": 432}]},
            {"type": "text", "x": 60, "y": 423, "width": 432, "text": "安全生产月经国务院批准，自1980年起在全国开展，时间为每年6月，旨在增强全民安全意识，提升公众安全素养，推动企业落实安全生产主体责任，促进安全生产形势持续稳定向好。", "fontSize": 13, "color": "#374151"},
            {"type": "group", "x": 60, "y": 500, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "开展安全生产月的意义", "color": "#c8161d", "width": 432}]},
            {"type": "group", "x": 60, "y": 542, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "square", "color": "#c8161d", "icon": "01", "label": "普及安全知识 提升全员安全素养"}, {"shape": "square", "color": "#a10f16", "icon": "02", "label": "强化安全意识 树立安全从业理念"}, {"shape": "square", "color": "#c8161d", "icon": "03", "label": "排查安全隐患 降低事故发生风险"}, {"shape": "square", "color": "#a10f16", "icon": "04", "label": "规范操作行为 杜绝违章违规作业"}, {"shape": "square", "color": "#c8161d", "icon": "05", "label": "演练应急技能 增强应急处置能力"}, {"shape": "square", "color": "#a10f16", "icon": "06", "label": "营造安全氛围 夯实安全生产根基"}, {"shape": "square", "color": "#c8161d", "icon": "07", "label": "强化技防管控 提升本质安全水平"}, {"shape": "square", "color": "#a10f16", "icon": "08", "label": "检验管理体系 完善预案实战能力"}, {"shape": "square", "color": "#c8161d", "icon": "09", "label": "夯实安全基础 保障企业稳定发展"}]},
            {"type": "group", "x": 522, "y": 212, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "安全生产责任“五落实”", "color": "#c8161d", "width": 432}]},
            {"type": "group", "x": 522, "y": 254, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#c8161d", "icon": "1", "label": "落实党政同责要求"}, {"shape": "circle", "color": "#c8161d", "icon": "2", "label": "落实安全一岗双责"}, {"shape": "circle", "color": "#c8161d", "icon": "3", "label": "落实组织领导机构"}, {"shape": "circle", "color": "#c8161d", "icon": "4", "label": "落实安全管理力量"}, {"shape": "circle", "color": "#c8161d", "icon": "5", "label": "落实安全报告制度"}]},
            {"type": "group", "x": 522, "y": 444, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "安全生产责任“五到位”", "color": "#c8161d", "width": 432}]},
            {"type": "group", "x": 522, "y": 486, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#c8161d", "icon": "1", "label": "安全责任到位"}, {"shape": "circle", "color": "#c8161d", "icon": "2", "label": "安全投入到位"}, {"shape": "circle", "color": "#c8161d", "icon": "3", "label": "安全培训到位"}, {"shape": "circle", "color": "#c8161d", "icon": "4", "label": "安全管理到位"}, {"shape": "circle", "color": "#c8161d", "icon": "5", "label": "应急救援到位"}]},
            {"type": "group", "x": 522, "y": 676, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "安全生产“六个零”目标", "color": "#c8161d", "width": 432}]},
            {"type": "group", "x": 522, "y": 718, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#c8161d", "icon": "1", "label": "零死亡事故"}, {"shape": "circle", "color": "#c8161d", "icon": "2", "label": "零重伤事故"}, {"shape": "circle", "color": "#c8161d", "icon": "3", "label": "零重大交通事故"}, {"shape": "circle", "color": "#c8161d", "icon": "4", "label": "零重大火灾事故"}, {"shape": "circle", "color": "#c8161d", "icon": "5", "label": "零重大设备事故"}, {"shape": "circle", "color": "#c8161d", "icon": "6", "label": "零职业病例"}]},
            {"type": "group", "x": 522, "y": 942, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "安全生产三项原则", "color": "#1c6fb0", "width": 432}]},
            {"type": "text", "x": 522, "y": 984, "width": 432, "text": "安全第一", "fontSize": 14, "fontWeight": "bold", "color": "#0f5488"},
            {"type": "text", "x": 522, "y": 1004, "width": 432, "text": "坚持在安全前提下组织生产经营，不能以牺牲生命为代价换取一时发展。", "fontSize": 12, "color": "#6b7280"},
            {"type": "text", "x": 522, "y": 1027, "width": 432, "text": "预防为主", "fontSize": 14, "fontWeight": "bold", "color": "#0f5488"},
            {"type": "text", "x": 522, "y": 1047, "width": 432, "text": "把安全工作重心放在事前，强化风险管控，消除隐患根源。", "fontSize": 12, "color": "#6b7280"},
            {"type": "text", "x": 522, "y": 1070, "width": 432, "text": "综合治理", "fontSize": 14, "fontWeight": "bold", "color": "#0f5488"},
            {"type": "text", "x": 522, "y": 1090, "width": 432, "text": "运用法治、经济、科技等多种手段协同推进安全生产工作。", "fontSize": 12, "color": "#6b7280"},
            {"type": "group", "x": 984, "y": 212, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "安全生产“五不能”", "color": "#1c6fb0", "width": 432}]},
            {"type": "group", "x": 984, "y": 254, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#ef4444", "icon": "✕", "label": "安全规程不能违"}, {"shape": "circle", "color": "#ef4444", "icon": "✕", "label": "安全意识不能少"}, {"shape": "circle", "color": "#ef4444", "icon": "✕", "label": "安全教育不能缺"}, {"shape": "circle", "color": "#ef4444", "icon": "✕", "label": "安全投入不能省"}, {"shape": "circle", "color": "#ef4444", "icon": "✕", "label": "安全管理不能松"}]},
            {"type": "image", "x": 1135, "y": 434, "width": 130, "height": 190, "src": "/templates/safety-month-grid-supervisor-icon.png"},
            {"type": "group", "x": 984, "y": 644, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "安全生产“八安八险”", "color": "#c8161d", "width": 432}]},
            {"type": "text", "x": 984, "y": 686, "width": 100, "text": "八安", "fontSize": 14, "fontWeight": "bold", "color": "#1c6fb0", "align": "center"},
            {"type": "text", "x": 1204, "y": 686, "width": 100, "text": "八险", "fontSize": 14, "fontWeight": "bold", "color": "#c8161d", "align": "center"},
            {"type": "group", "x": 984, "y": 708, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "diamond", "color": "#1c6fb0", "icon": "安", "label": "遵章守纪为安"}, {"shape": "diamond", "color": "#1c6fb0", "icon": "安", "label": "谦虚谨慎为安"}, {"shape": "diamond", "color": "#1c6fb0", "icon": "安", "label": "精力集中为安"}, {"shape": "diamond", "color": "#1c6fb0", "icon": "安", "label": "劳保齐全为安"}, {"shape": "diamond", "color": "#1c6fb0", "icon": "安", "label": "防微杜渐为安"}, {"shape": "diamond", "color": "#1c6fb0", "icon": "安", "label": "现场整洁为安"}, {"shape": "diamond", "color": "#1c6fb0", "icon": "安", "label": "事前预防为安"}, {"shape": "diamond", "color": "#1c6fb0", "icon": "安", "label": "严格要求为安"}]},
            {"type": "group", "x": 1204, "y": 708, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "diamond", "color": "#ef4444", "icon": "险", "label": "违章蛮干为险"}, {"shape": "diamond", "color": "#ef4444", "icon": "险", "label": "逞强好胜为险"}, {"shape": "diamond", "color": "#ef4444", "icon": "险", "label": "心神不定为险"}, {"shape": "diamond", "color": "#ef4444", "icon": "险", "label": "麻痹大意为险"}, {"shape": "diamond", "color": "#ef4444", "icon": "险", "label": "心存侥幸为险"}, {"shape": "diamond", "color": "#ef4444", "icon": "险", "label": "器具杂乱为险"}, {"shape": "diamond", "color": "#ef4444", "icon": "险", "label": "事后抢救为险"}, {"shape": "diamond", "color": "#ef4444", "icon": "险", "label": "松松垮垮为险"}]},
            {"type": "group", "x": 984, "y": 1000, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "安全生产事故“四不放过”", "color": "#c8161d", "width": 432}]},
            {"type": "group", "x": 984, "y": 1042, "width": 432, "height": 144, "children": [{"type": "circle", "x": 0, "y": 0, "radius": 11.0, "fill": "#c8161d"}, {"type": "text", "x": 0, "y": 4.0, "width": 22, "text": "1", "fontSize": 11, "fill": "#ffffff", "fontWeight": "bold", "textAlign": "center"}, {"type": "text", "x": 30, "y": 2, "width": 402, "text": "事故原因未查清不放过", "fontSize": 13, "fill": "#374151"}, {"type": "circle", "x": 0, "y": 36, "radius": 11.0, "fill": "#c8161d"}, {"type": "text", "x": 0, "y": 40.0, "width": 22, "text": "2", "fontSize": 11, "fill": "#ffffff", "fontWeight": "bold", "textAlign": "center"}, {"type": "text", "x": 30, "y": 38, "width": 402, "text": "责任人员未处理不放过", "fontSize": 13, "fill": "#374151"}, {"type": "circle", "x": 0, "y": 72, "radius": 11.0, "fill": "#c8161d"}, {"type": "text", "x": 0, "y": 76.0, "width": 22, "text": "3", "fontSize": 11, "fill": "#ffffff", "fontWeight": "bold", "textAlign": "center"}, {"type": "text", "x": 30, "y": 74, "width": 402, "text": "整改措施未落实不放过", "fontSize": 13, "fill": "#374151"}, {"type": "circle", "x": 0, "y": 108, "radius": 11.0, "fill": "#c8161d"}, {"type": "text", "x": 0, "y": 112.0, "width": 22, "text": "4", "fontSize": 11, "fill": "#ffffff", "fontWeight": "bold", "textAlign": "center"}, {"type": "text", "x": 30, "y": 110, "width": 402, "text": "有关人员未受到教育不放过", "fontSize": 13, "fill": "#374151"}]},
            {"type": "group", "x": 1446, "y": 212, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "安全生产“十查十禁”", "color": "#c8161d", "width": 432}]},
            {"type": "group", "x": 1446, "y": 254, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "square", "color": "#c8161d", "icon": "查", "label": "防护器材"}, {"shape": "square", "color": "#c8161d", "icon": "查", "label": "通道出口"}, {"shape": "square", "color": "#c8161d", "icon": "查", "label": "照明标识"}, {"shape": "square", "color": "#c8161d", "icon": "查", "label": "电气线路"}, {"shape": "square", "color": "#c8161d", "icon": "查", "label": "用火用电"}]},
            {"type": "group", "x": 1666, "y": 254, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "square", "color": "#a10f16", "icon": "禁", "label": "毁坏挪用"}, {"shape": "square", "color": "#a10f16", "icon": "禁", "label": "堵塞封堵"}, {"shape": "square", "color": "#a10f16", "icon": "禁", "label": "遮挡损坏"}, {"shape": "square", "color": "#a10f16", "icon": "禁", "label": "乱拉乱接"}, {"shape": "square", "color": "#a10f16", "icon": "禁", "label": "违规操作"}]},
            {"type": "image", "x": 1602, "y": 434, "width": 120, "height": 175, "src": "/templates/safety-month-grid-inspector-icon.png"},
            {"type": "group", "x": 1446, "y": 629, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "安全生产常用术语", "color": "#c8161d", "width": 432}]},
            {"type": "text", "x": 1446, "y": 671, "width": 136, "text": "红线意识", "fontSize": 13, "fontWeight": "bold", "color": "#a10f16", "align": "center"},
            {"type": "text", "x": 1446, "y": 691, "width": 136, "text": "人命关天，发展决不能以牺牲生命为代价，这是不可逾越的红线。", "fontSize": 10.5, "color": "#6b7280", "align": "center"},
            {"type": "text", "x": 1594, "y": 671, "width": 136, "text": "三基建设", "fontSize": 13, "fontWeight": "bold", "color": "#a10f16", "align": "center"},
            {"type": "text", "x": 1594, "y": 691, "width": 136, "text": "抓基层、打基础、苦练基本功，夯实安全生产根基。", "fontSize": 10.5, "color": "#6b7280", "align": "center"},
            {"type": "text", "x": 1742, "y": 671, "width": 136, "text": "三不伤害", "fontSize": 13, "fontWeight": "bold", "color": "#a10f16", "align": "center"},
            {"type": "text", "x": 1742, "y": 691, "width": 136, "text": "不伤害自己、不伤害他人、不被他人伤害。", "fontSize": 10.5, "color": "#6b7280", "align": "center"},
            {"type": "group", "x": 1446, "y": 756, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "消防安全“四个能力”", "color": "#c8161d", "width": 432}]},
            {"type": "group", "x": 1446, "y": 798, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#c8161d", "icon": "1", "label": "检查消除火灾隐患能力"}, {"shape": "circle", "color": "#c8161d", "icon": "2", "label": "组织扑救初起火灾能力"}]},
            {"type": "group", "x": 1666, "y": 798, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#c8161d", "icon": "3", "label": "组织人员疏散逃生能力"}, {"shape": "circle", "color": "#c8161d", "icon": "4", "label": "消防宣传教育培训能力"}]},
            {"type": "group", "x": 1446, "y": 886, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "安全宣传“五进”", "color": "#1c6fb0", "width": 432}]},
            {"type": "group", "x": 1446, "y": 928, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#1c6fb0", "icon": "企", "label": "进企业 负责人带头讲安全课"}, {"shape": "circle", "color": "#1c6fb0", "icon": "农", "label": "进农村 普及用电用气安全知识"}, {"shape": "circle", "color": "#1c6fb0", "icon": "社", "label": "进社区 建安全体验角+互助培训"}, {"shape": "circle", "color": "#1c6fb0", "icon": "校", "label": "进学校 开展小手拉大手活动"}, {"shape": "circle", "color": "#1c6fb0", "icon": "家", "label": "进家庭 敲门行动排查家中隐患"}]},
            {"type": "group", "x": 1908, "y": 212, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "安全生产十六字方针", "color": "#1c6fb0", "width": 432}]},
            {"type": "rect", "x": 1908, "y": 251, "width": 80, "height": 20, "fill": "#1c6fb0", "rx": 3},
            {"type": "text", "x": 1908, "y": 254, "width": 80, "text": "四不放过", "fontSize": 12, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 1908, "y": 280, "width": 432, "text": "隐患未查清不放过、责任未追究不放过、整改未落实不放过、人员未受教育不放过。", "fontSize": 12, "color": "#374151"},
            {"type": "rect", "x": 1908, "y": 325, "width": 80, "height": 20, "fill": "#1c6fb0", "rx": 3},
            {"type": "text", "x": 1908, "y": 328, "width": 80, "text": "五要素", "fontSize": 12, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 1908, "y": 354, "width": 432, "text": "安全责任、安全投入、安全培训、安全管理、应急救援，五者缺一不可。", "fontSize": 12, "color": "#374151"},
            {"type": "image", "x": 2064, "y": 383, "width": 120, "height": 175, "src": "/templates/safety-month-grid-worker-icon.png"},
            {"type": "group", "x": 1908, "y": 578, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "检查监督“四不两直”", "color": "#1c6fb0", "width": 432}]},
            {"type": "group", "x": 1908, "y": 620, "children": [], "componentKind": "icon-list", "componentData": [{"shape": "circle", "color": "#1c6fb0", "icon": "不", "label": "不发通知"}, {"shape": "circle", "color": "#1c6fb0", "icon": "不", "label": "不打招呼"}, {"shape": "circle", "color": "#1c6fb0", "icon": "不", "label": "不听汇报"}, {"shape": "circle", "color": "#1c6fb0", "icon": "不", "label": "不用陪同接待"}, {"shape": "circle", "color": "#0f5488", "icon": "直", "label": "直奔基层"}, {"shape": "circle", "color": "#0f5488", "icon": "直", "label": "直插现场"}]},
            {"type": "group", "x": 1908, "y": 844, "children": [], "componentKind": "ribbon-title", "componentData": [{"text": "日常安全提醒", "color": "#1c6fb0", "width": 432}]},
            {"type": "group", "x": 1908, "y": 886, "width": 432, "height": 144, "children": [{"type": "circle", "x": 0, "y": 0, "radius": 11.0, "fill": "#1c6fb0"}, {"type": "text", "x": 0, "y": 4.0, "width": 22, "text": "1", "fontSize": 11, "fill": "#ffffff", "fontWeight": "bold", "textAlign": "center"}, {"type": "text", "x": 30, "y": 2, "width": 402, "text": "用电用气规范操作 人走断电断气", "fontSize": 13, "fill": "#374151"}, {"type": "circle", "x": 0, "y": 36, "radius": 11.0, "fill": "#1c6fb0"}, {"type": "text", "x": 0, "y": 40.0, "width": 22, "text": "2", "fontSize": 11, "fill": "#ffffff", "fontWeight": "bold", "textAlign": "center"}, {"type": "text", "x": 30, "y": 38, "width": 402, "text": "楼道通道保持畅通 杜绝堆物占用", "fontSize": 13, "fill": "#374151"}, {"type": "circle", "x": 0, "y": 72, "radius": 11.0, "fill": "#1c6fb0"}, {"type": "text", "x": 0, "y": 76.0, "width": 22, "text": "3", "fontSize": 11, "fill": "#ffffff", "fontWeight": "bold", "textAlign": "center"}, {"type": "text", "x": 30, "y": 74, "width": 402, "text": "灭火器材定期检查 确保完好有效", "fontSize": 13, "fill": "#374151"}, {"type": "circle", "x": 0, "y": 108, "radius": 11.0, "fill": "#1c6fb0"}, {"type": "text", "x": 0, "y": 112.0, "width": 22, "text": "4", "fontSize": 11, "fill": "#ffffff", "fontWeight": "bold", "textAlign": "center"}, {"type": "text", "x": 30, "y": 110, "width": 402, "text": "发现隐患及时上报 不存侥幸心理", "fontSize": 13, "fill": "#374151"}]},
            {"type": "rect", "x": 0, "y": 1225, "width": 2400, "height": 60, "fill": "#c8161d"},
            {"type": "text", "x": 0, "y": 1241, "width": 2400, "text": "人人尽责 · 安全你我", "fontSize": 22, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
        ],
    },
    {
        "id": "tpl-ad-realestate",
        "name": "楼盘品鉴海报",
        "category": "广告设计",
        "scene": "宣传展板",
        "industry": "家居地产",
        "canvas_width": 800,
        "canvas_height": 1000,
        "background": "#0f172a",
        "thumbnail": thumb("ad-realestate", 300, 375),
        "elements": [
            {"type": "rect", "x": 60, "y": 60, "width": 680, "height": 3, "fill": "#d4af37"},
            {"type": "rect", "x": 60, "y": 910, "width": 680, "height": 3, "fill": "#d4af37"},
            {"type": "text", "x": 60, "y": 160, "width": 680, "text": "臻藏 · 城市之上", "fontSize": 54, "fontWeight": "bold", "color": "#d4af37", "align": "center"},
            {"type": "text", "x": 60, "y": 240, "width": 680, "text": "臻稀楼王 甄选而生", "fontSize": 20, "color": "#e2e8f0", "align": "center"},
            {"type": "rect", "x": 300, "y": 320, "width": 200, "height": 2, "fill": "#475569"},
            {"type": "text", "x": 100, "y": 400, "width": 600, "text": "地铁上盖 · 双学区配套 · 环城公园首排", "fontSize": 22, "color": "#cbd5e1", "align": "center"},
            {"type": "text", "x": 100, "y": 450, "width": 600, "text": "建面约 89-143㎡ 甄稀墅质大宅", "fontSize": 18, "color": "#94a3b8", "align": "center"},
            {"type": "rect", "x": 300, "y": 780, "width": 200, "height": 60, "fill": "#d4af37", "rx": 4},
            {"type": "text", "x": 300, "y": 798, "width": 200, "text": "预约品鉴", "fontSize": 22, "fontWeight": "bold", "color": "#0f172a", "align": "center"},
            {"type": "text", "x": 60, "y": 860, "width": 680, "text": "咨询热线：400-＿＿＿-＿＿＿＿", "fontSize": 16, "color": "#94a3b8", "align": "center"},
        ],
    },
    {
        "id": "tpl-poster-flash-sale",
        "name": "限时闪购海报",
        "category": "宣传海报",
        "scene": "促销活动",
        "industry": "电商零售",
        "canvas_width": 600,
        "canvas_height": 800,
        "background": "#fff1f2",
        "thumbnail": thumb("poster-flash-sale", 300, 400),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 600, "height": 260, "fill": "#f43f5e"},
            {"type": "text", "x": 0, "y": 50, "width": 600, "text": "周末闪购 48小时", "fontSize": 44, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 130, "width": 600, "text": "低至 5 折 手慢无", "fontSize": 24, "color": "#fff1f2", "align": "center"},
            {"type": "rect", "x": 220, "y": 180, "width": 160, "height": 50, "fill": "#ffffff", "rx": 25},
            {"type": "text", "x": 220, "y": 195, "width": 160, "text": "立即抢购", "fontSize": 20, "fontWeight": "bold", "color": "#f43f5e", "align": "center"},
            {"type": "text", "x": 40, "y": 300, "width": 520, "text": "各品类折扣力度", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {
                "type": "group",
                "x": 40,
                "y": 350,
                "children": [],
                "componentKind": "progress-bars",
                "componentData": [
                    {"label": "服饰", "value": 70, "color": "#f97316"},
                    {"label": "美妆", "value": 55, "color": "#ec4899"},
                    {"label": "数码", "value": 85, "color": "#38bdf8"},
                ],
            },
            {"type": "text", "x": 40, "y": 700, "width": 520, "text": "活动时间：本周六 00:00 - 周日 24:00", "fontSize": 16, "color": "#6b7280", "align": "center"},
        ],
    },
    {
        "id": "tpl-print-pricelist",
        "name": "轻食价目单",
        "category": "印刷制品",
        "scene": "门店物料",
        "industry": "餐饮美食",
        "canvas_width": 600,
        "canvas_height": 850,
        "background": "#fff7ed",
        "thumbnail": thumb("print-pricelist", 300, 425),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 600, "height": 140, "fill": "#f97316"},
            {"type": "text", "x": 0, "y": 45, "width": 600, "text": "轻食价目单", "fontSize": 36, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 95, "width": 600, "text": "新鲜现做 · 健康轻负担", "fontSize": 16, "color": "#ffedd5", "align": "center"},
            {
                "type": "group",
                "x": 165,
                "y": 180,
                "children": [],
                "componentKind": "grid-table",
                "componentData": {
                    "rows": [
                        ["单品", "热量", "价格"],
                        ["轻食沙拉", "320kcal", "28"],
                        ["牛油果虾", "280kcal", "32"],
                        ["低脂鸡卷", "260kcal", "22"],
                        ["鲜榨果昔", "150kcal", "18"],
                    ],
                    "theme": "orange",
                    "fontFamily": "sans-serif",
                    "fontSize": 13,
                    "bold": False,
                    "italic": False,
                    "underline": False,
                    "align": "left",
                    "merges": [],
                },
            },
            {"type": "text", "x": 40, "y": 420, "width": 520, "text": "以上价格仅供参考，具体以门店为准", "fontSize": 14, "color": "#9ca3af", "align": "center"},
            {"type": "rect", "x": 0, "y": 770, "width": 600, "height": 80, "fill": "#f97316"},
            {"type": "text", "x": 0, "y": 800, "width": 600, "text": "地址：XX市XX路轻食生活馆", "fontSize": 16, "color": "#ffffff", "align": "center"},
        ],
    },
    {
        "id": "tpl-ecom-presale",
        "name": "新品预售海报",
        "category": "电商营销",
        "scene": "促销活动",
        "industry": "电商零售",
        "canvas_width": 800,
        "canvas_height": 800,
        "background": "#111827",
        "thumbnail": thumb("ecom-presale", 300, 300),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 800, "height": 8, "fill": "#22d3ee"},
            {"type": "text", "x": 0, "y": 140, "width": 800, "text": "新品预售", "fontSize": 64, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 230, "width": 800, "text": "预售立减 ¥200", "fontSize": 28, "color": "#22d3ee", "align": "center"},
            {"type": "text", "x": 0, "y": 500, "width": 800, "text": "原价 ¥1999", "fontSize": 20, "color": "#6b7280", "align": "center"},
            {"type": "rect", "x": 340, "y": 508, "width": 120, "height": 2, "fill": "#6b7280"},
            {"type": "text", "x": 0, "y": 540, "width": 800, "text": "预售价 ¥1799", "fontSize": 48, "fontWeight": "bold", "color": "#22d3ee", "align": "center"},
            {"type": "rect", "x": 300, "y": 650, "width": 200, "height": 64, "fill": "#22d3ee", "rx": 32},
            {"type": "text", "x": 300, "y": 670, "width": 200, "text": "立即预定", "fontSize": 22, "fontWeight": "bold", "color": "#111827", "align": "center"},
            {"type": "text", "x": 0, "y": 750, "width": 800, "text": "预售时间：即日起至月底", "fontSize": 16, "color": "#9ca3af", "align": "center"},
        ],
    },
    {
        "id": "tpl-social-digest",
        "name": "干货合集公众号封面",
        "category": "自媒体配图",
        "scene": "内容封面",
        "industry": "通用场景",
        "canvas_width": 900,
        "canvas_height": 500,
        "background": "#fef3c7",
        "thumbnail": thumb("social-digest", 300, 167),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 320, "height": 500, "fill": "#f59e0b"},
            {"type": "text", "x": 40, "y": 40, "width": 240, "text": "第 12 期", "fontSize": 18, "fontWeight": "bold", "color": "#fffbeb"},
            {"type": "text", "x": 40, "y": 170, "width": 240, "text": "12", "fontSize": 120, "fontWeight": "bold", "color": "#ffffff"},
            {"type": "text", "x": 360, "y": 160, "width": 500, "text": "干货合集", "fontSize": 48, "fontWeight": "bold", "color": "#78350f"},
            {"type": "text", "x": 360, "y": 250, "width": 480, "text": "5 个提升效率的实用技巧，收藏这一篇就够了", "fontSize": 20, "color": "#92400e"},
            {"type": "rect", "x": 360, "y": 320, "width": 140, "height": 40, "fill": "#78350f", "rx": 20},
            {"type": "text", "x": 360, "y": 332, "width": 140, "text": "职场干货", "fontSize": 16, "color": "#fef3c7", "align": "center"},
        ],
    },
    {
        "id": "tpl-handnews-recycle",
        "name": "垃圾分类环保手抄报",
        "category": "创意手作",
        "scene": "校园手抄报",
        "industry": "教育培训",
        "canvas_width": 700,
        "canvas_height": 900,
        "background": "#ecfdf5",
        "thumbnail": thumb("handnews-recycle", 300, 386),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 700, "height": 160, "fill": "#16a34a"},
            {"type": "text", "x": 0, "y": 55, "width": 700, "text": "垃圾分类 从我做起", "fontSize": 40, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 115, "width": 700, "text": "分类投放 · 变废为宝 · 守护家园", "fontSize": 18, "color": "#dcfce7", "align": "center"},
            {
                "type": "group",
                "x": 196,
                "y": 220,
                "children": [],
                "componentKind": "swot",
                "componentData": [
                    {"title": "可回收物", "body": "纸张、塑料瓶\n玻璃、金属", "color": "#3b82f6"},
                    {"title": "厨余垃圾", "body": "剩菜剩饭\n果皮菜叶", "color": "#22c55e"},
                    {"title": "有害垃圾", "body": "废电池\n过期药品", "color": "#ef4444"},
                    {"title": "其他垃圾", "body": "纸巾灰土\n受污染物品", "color": "#6b7280"},
                ],
            },
            {"type": "text", "x": 60, "y": 520, "width": 580, "text": "小小举动，大大改变——从今天开始，做分类小达人", "fontSize": 20, "fontWeight": "bold", "color": "#166534", "align": "center"},
            {"type": "rect", "x": 0, "y": 840, "width": 700, "height": 60, "fill": "#16a34a"},
            {"type": "text", "x": 0, "y": 860, "width": 700, "text": "班级：＿＿＿＿   姓名：＿＿＿＿", "fontSize": 16, "color": "#ffffff", "align": "center"},
        ],
    },
    {
        "id": "tpl-office-weekly",
        "name": "部门工作周报",
        "category": "职场文档",
        "scene": "通知公文",
        "industry": "企业办公",
        "canvas_width": 700,
        "canvas_height": 900,
        "background": "#ffffff",
        "thumbnail": thumb("office-weekly", 300, 386),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 700, "height": 110, "fill": "#1e40af"},
            {"type": "text", "x": 0, "y": 35, "width": 700, "text": "部门工作周报", "fontSize": 32, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 82, "width": 700, "text": "第＿＿周  ｜  汇报人：＿＿＿＿", "fontSize": 14, "color": "#bfdbfe", "align": "center"},
            {"type": "rect", "x": 40, "y": 150, "width": 6, "height": 24, "fill": "#1e40af"},
            {"type": "text", "x": 60, "y": 148, "width": 300, "text": "本周任务进度", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {
                "type": "group",
                "x": 60,
                "y": 195,
                "children": [],
                "componentKind": "bar-chart",
                "componentData": [
                    {"label": "需求评审", "value": 100, "color": "#8b5cf6"},
                    {"label": "开发联调", "value": 80, "color": "#38bdf8"},
                    {"label": "测试验收", "value": 60, "color": "#22c55e"},
                    {"label": "文档归档", "value": 40, "color": "#f59e0b"},
                ],
            },
            {"type": "rect", "x": 40, "y": 430, "width": 6, "height": 24, "fill": "#1e40af"},
            {"type": "text", "x": 60, "y": 428, "width": 300, "text": "本周工作总结", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 472, "width": 620, "text": "• 完成需求评审，明确了核心功能边界\n• 开发进度符合预期，联调阶段已启动\n• 测试用例覆盖率达到 80% 以上", "fontSize": 16, "color": "#374151"},
            {"type": "rect", "x": 40, "y": 620, "width": 6, "height": 24, "fill": "#1e40af"},
            {"type": "text", "x": 60, "y": 618, "width": 300, "text": "下周计划", "fontSize": 20, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "text", "x": 40, "y": 662, "width": 620, "text": "• 完成剩余联调工作并提测\n• 补齐测试用例，推进验收\n• 输出功能文档并归档", "fontSize": 16, "color": "#374151"},
            {"type": "text", "x": 380, "y": 830, "width": 260, "text": "＿＿＿＿年＿＿月＿＿日", "fontSize": 14, "color": "#9ca3af", "align": "right"},
        ],
    },
    {
        "id": "tpl-handnews-coalgas",
        "name": "预防一氧化碳中毒手抄报",
        "category": "创意手作",
        "scene": "校园手抄报",
        "industry": "教育培训",
        "canvas_width": 700,
        "canvas_height": 900,
        "background": "#f0f9ff",
        "thumbnail": thumb("handnews-coalgas", 300, 386),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 700, "height": 150, "fill": "#0ea5e9"},
            {"type": "text", "x": 0, "y": 45, "width": 700, "text": "冬季取暖 预防中毒", "fontSize": 38, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 108, "width": 700, "text": "安全过冬 · 平安相伴", "fontSize": 18, "color": "#e0f2fe", "align": "center"},
            {"type": "rect", "x": 40, "y": 180, "width": 620, "height": 190, "fill": "#ffffff", "rx": 16},
            {"type": "text", "x": 68, "y": 204, "width": 560, "text": "什么是一氧化碳中毒", "fontSize": 20, "fontWeight": "bold", "color": "#0369a1"},
            {"type": "text", "x": 68, "y": 244, "width": 560, "text": "一氧化碳是无色无味的气体，煤炭、天然气等燃料燃烧不充分时产生。吸入后会出现头痛、头晕、恶心、四肢无力等症状，严重时可致命。", "fontSize": 16, "color": "#374151"},
            {"type": "rect", "x": 40, "y": 400, "width": 620, "height": 240, "fill": "#ffffff", "rx": 16},
            {"type": "text", "x": 68, "y": 424, "width": 560, "text": "预防措施", "fontSize": 20, "fontWeight": "bold", "color": "#0369a1"},
            {"type": "text", "x": 68, "y": 464, "width": 560, "text": "1. 室内使用煤气、木炭取暖时保持通风\n2. 定期检查燃气设备和排烟管道\n3. 不在密闭空间使用炭火取暖\n4. 安装一氧化碳报警器更安心\n5. 头晕恶心要立即开窗通风、离开现场", "fontSize": 16, "color": "#374151"},
            {"type": "rect", "x": 40, "y": 660, "width": 620, "height": 140, "fill": "#fef2f2", "rx": 16},
            {"type": "text", "x": 68, "y": 684, "width": 560, "text": "紧急处置", "fontSize": 20, "fontWeight": "bold", "color": "#dc2626"},
            {"type": "text", "x": 68, "y": 722, "width": 560, "text": "发现中毒者立即打开门窗，将人转移到空气新鲜处，拨打 120 急救电话。", "fontSize": 16, "color": "#374151"},
            {"type": "text", "x": 0, "y": 840, "width": 700, "text": "班级：＿＿＿＿   姓名：＿＿＿＿", "fontSize": 16, "color": "#0369a1", "align": "center"},
        ],
    },
    {
        "id": "tpl-print-supermarket-flyer",
        "name": "超市促销宣传单",
        "category": "印刷制品",
        "scene": "门店物料",
        "industry": "电商零售",
        "canvas_width": 700,
        "canvas_height": 900,
        "background": "#e0f2fe",
        "thumbnail": thumb("print-supermarket-flyer", 300, 386),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 700, "height": 140, "fill": "#0284c7"},
            {"type": "text", "x": 40, "y": 30, "width": 400, "text": "惠民生活超市", "fontSize": 26, "fontWeight": "bold", "color": "#ffffff"},
            {"type": "text", "x": 40, "y": 72, "width": 400, "text": "10.20 - 10.24 全场特惠", "fontSize": 16, "color": "#e0f2fe"},
            {"type": "text", "x": 0, "y": 170, "width": 700, "text": "惊喜好价 天天优惠", "fontSize": 32, "fontWeight": "bold", "color": "#0c4a6e", "align": "center"},
            {"type": "rect", "x": 50, "y": 260, "width": 300, "height": 110, "fill": "#ffffff", "rx": 10},
            {"type": "text", "x": 70, "y": 276, "width": 260, "text": "新鲜苹果", "fontSize": 17, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "rect", "x": 70, "y": 316, "width": 100, "height": 36, "fill": "#f97316", "rx": 6},
            {"type": "text", "x": 70, "y": 324, "width": 100, "text": "¥6.9", "fontSize": 18, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "rect", "x": 370, "y": 260, "width": 300, "height": 110, "fill": "#ffffff", "rx": 10},
            {"type": "text", "x": 390, "y": 276, "width": 260, "text": "优质大米", "fontSize": 17, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "rect", "x": 390, "y": 316, "width": 100, "height": 36, "fill": "#f97316", "rx": 6},
            {"type": "text", "x": 390, "y": 324, "width": 100, "text": "¥39.9", "fontSize": 18, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "rect", "x": 50, "y": 390, "width": 300, "height": 110, "fill": "#ffffff", "rx": 10},
            {"type": "text", "x": 70, "y": 406, "width": 260, "text": "精选牛肉", "fontSize": 17, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "rect", "x": 70, "y": 446, "width": 100, "height": 36, "fill": "#f97316", "rx": 6},
            {"type": "text", "x": 70, "y": 454, "width": 100, "text": "¥45", "fontSize": 18, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "rect", "x": 370, "y": 390, "width": 300, "height": 110, "fill": "#ffffff", "rx": 10},
            {"type": "text", "x": 390, "y": 406, "width": 260, "text": "儿童牛奶", "fontSize": 17, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "rect", "x": 390, "y": 446, "width": 100, "height": 36, "fill": "#f97316", "rx": 6},
            {"type": "text", "x": 390, "y": 454, "width": 100, "text": "¥28", "fontSize": 18, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "rect", "x": 50, "y": 520, "width": 300, "height": 110, "fill": "#ffffff", "rx": 10},
            {"type": "text", "x": 70, "y": 536, "width": 260, "text": "厨房纸巾", "fontSize": 17, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "rect", "x": 70, "y": 576, "width": 100, "height": 36, "fill": "#f97316", "rx": 6},
            {"type": "text", "x": 70, "y": 584, "width": 100, "text": "¥15.9", "fontSize": 18, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "rect", "x": 370, "y": 520, "width": 300, "height": 110, "fill": "#ffffff", "rx": 10},
            {"type": "text", "x": 390, "y": 536, "width": 260, "text": "洗洁精", "fontSize": 17, "fontWeight": "bold", "color": "#1f2937"},
            {"type": "rect", "x": 390, "y": 576, "width": 100, "height": 36, "fill": "#f97316", "rx": 6},
            {"type": "text", "x": 390, "y": 584, "width": 100, "text": "¥9.9", "fontSize": 18, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "rect", "x": 0, "y": 800, "width": 700, "height": 100, "fill": "#0284c7"},
            {"type": "text", "x": 0, "y": 830, "width": 700, "text": "地址：XX市XX路惠民超市  电话：XXX-XXXXXXX", "fontSize": 14, "color": "#ffffff", "align": "center"},
        ],
    },
    {
        "id": "tpl-board-party-building",
        "name": "党建主题宣传展板",
        "category": "广告设计",
        "scene": "宣传展板",
        "industry": "企业办公",
        "canvas_width": 1000,
        "canvas_height": 1000,
        "background": "#c1272d",
        "thumbnail": "/templates/party-building-bg.png",
        "elements": [
            {"type": "image", "x": 0, "y": 0, "width": 1000, "height": 1000, "src": "/templates/party-building-bg.png"},
            {"type": "text", "x": 100, "y": 260, "width": 800, "text": "喜迎华诞 礼赞盛世", "fontSize": 62, "fontWeight": "bold", "color": "#fde047", "align": "center"},
            {"type": "text", "x": 100, "y": 370, "width": 800, "text": "党建引领 · 凝心聚力 · 共谱新篇", "fontSize": 26, "color": "#fef3c7", "align": "center"},
        ],
    },
    {
        "id": "tpl-poster-kids-art-class",
        "name": "儿童美术班招生海报",
        "category": "宣传海报",
        "scene": "宣传展板",
        "industry": "教育培训",
        "canvas_width": 900,
        "canvas_height": 1200,
        "background": "#32becf",
        "thumbnail": thumb("kids-art-class", 300, 400),
        "elements": [
            {"type": "rect", "x": 0, "y": 0, "width": 900, "height": 150, "fill": "#4dd9e0"},
            {"type": "rect", "x": 0, "y": 150, "width": 900, "height": 150, "fill": "#44d0da"},
            {"type": "rect", "x": 0, "y": 300, "width": 900, "height": 150, "fill": "#3bc7d5"},
            {"type": "rect", "x": 0, "y": 450, "width": 900, "height": 150, "fill": "#32becf"},
            {"type": "rect", "x": 0, "y": 600, "width": 900, "height": 150, "fill": "#2ab6c9"},
            {"type": "rect", "x": 0, "y": 750, "width": 900, "height": 150, "fill": "#21adc3"},
            {"type": "rect", "x": 0, "y": 900, "width": 900, "height": 150, "fill": "#18a4be"},
            {"type": "rect", "x": 0, "y": 1050, "width": 900, "height": 150, "fill": "#0f9bb8"},
            {"type": "group", "x": 18, "y": 124, "children": [{"type": "circle", "x": 13, "y": 5, "radius": 121, "fill": "#ffffff"}, {"type": "circle", "x": 206, "y": 28, "radius": 110, "fill": "#ffffff"}, {"type": "circle", "x": 410, "y": 26, "radius": 96, "fill": "#ffffff"}, {"type": "circle", "x": 634, "y": 0, "radius": 99, "fill": "#ffffff"}, {"type": "circle", "x": 838, "y": 46, "radius": 100, "fill": "#ffffff"}, {"type": "circle", "x": 8, "y": 214, "radius": 133, "fill": "#ffffff"}, {"type": "circle", "x": 190, "y": 200, "radius": 134, "fill": "#ffffff"}, {"type": "circle", "x": 327, "y": 228, "radius": 107, "fill": "#ffffff"}, {"type": "circle", "x": 496, "y": 183, "radius": 107, "fill": "#ffffff"}, {"type": "circle", "x": 694, "y": 187, "radius": 118, "fill": "#ffffff"}, {"type": "circle", "x": 849, "y": 198, "radius": 117, "fill": "#ffffff"}, {"type": "circle", "x": 0, "y": 370, "radius": 103, "fill": "#ffffff"}, {"type": "circle", "x": 195, "y": 392, "radius": 108, "fill": "#ffffff"}, {"type": "circle", "x": 354, "y": 393, "radius": 107, "fill": "#ffffff"}, {"type": "circle", "x": 529, "y": 408, "radius": 105, "fill": "#ffffff"}, {"type": "circle", "x": 682, "y": 398, "radius": 130, "fill": "#ffffff"}, {"type": "circle", "x": 853, "y": 383, "radius": 134, "fill": "#ffffff"}, {"type": "circle", "x": 3, "y": 571, "radius": 125, "fill": "#ffffff"}, {"type": "circle", "x": 210, "y": 575, "radius": 97, "fill": "#ffffff"}, {"type": "circle", "x": 440, "y": 592, "radius": 118, "fill": "#ffffff"}, {"type": "circle", "x": 656, "y": 565, "radius": 123, "fill": "#ffffff"}, {"type": "circle", "x": 847, "y": 581, "radius": 113, "fill": "#ffffff"}]},
            {"type": "group", "x": 300, "y": 40, "children": [{"type": "circle", "x": 100, "y": 100, "radius": 50, "fill": "rgba(255,209,102,0.55)"}, {"type": "line", "x1": 245, "y1": 150, "x2": 295, "y2": 150, "stroke": "#ffd166", "strokeWidth": 10, "strokeLineCap": "round"}, {"type": "line", "x1": 232, "y1": 198, "x2": 276, "y2": 223, "stroke": "#ffd166", "strokeWidth": 10, "strokeLineCap": "round"}, {"type": "line", "x1": 198, "y1": 232, "x2": 223, "y2": 276, "stroke": "#ffd166", "strokeWidth": 10, "strokeLineCap": "round"}, {"type": "line", "x1": 150, "y1": 245, "x2": 150, "y2": 295, "stroke": "#ffd166", "strokeWidth": 10, "strokeLineCap": "round"}, {"type": "line", "x1": 102, "y1": 232, "x2": 77, "y2": 276, "stroke": "#ffd166", "strokeWidth": 10, "strokeLineCap": "round"}, {"type": "line", "x1": 68, "y1": 198, "x2": 24, "y2": 223, "stroke": "#ffd166", "strokeWidth": 10, "strokeLineCap": "round"}, {"type": "line", "x1": 55, "y1": 150, "x2": 5, "y2": 150, "stroke": "#ffd166", "strokeWidth": 10, "strokeLineCap": "round"}, {"type": "line", "x1": 68, "y1": 102, "x2": 24, "y2": 77, "stroke": "#ffd166", "strokeWidth": 10, "strokeLineCap": "round"}, {"type": "line", "x1": 102, "y1": 68, "x2": 77, "y2": 24, "stroke": "#ffd166", "strokeWidth": 10, "strokeLineCap": "round"}, {"type": "line", "x1": 150, "y1": 55, "x2": 150, "y2": 5, "stroke": "#ffd166", "strokeWidth": 10, "strokeLineCap": "round"}, {"type": "line", "x1": 198, "y1": 68, "x2": 223, "y2": 24, "stroke": "#ffd166", "strokeWidth": 10, "strokeLineCap": "round"}, {"type": "line", "x1": 232, "y1": 102, "x2": 276, "y2": 77, "stroke": "#ffd166", "strokeWidth": 10, "strokeLineCap": "round"}]},
            {"type": "text", "x": 6, "y": 130, "width": 894, "text": "缤纷美术", "fontSize": 72, "fontWeight": "bold", "color": "#4c1d95", "align": "center"},
            {"type": "text", "x": 0, "y": 120, "width": 900, "text": "缤纷美术", "fontSize": 72, "fontWeight": "bold", "color": "#8b5cf6", "align": "center", "stroke": "#ffffff", "strokeWidth": 10, "shadowColor": "rgba(0,0,0,0.2)", "shadowBlur": 3, "shadowOffsetX": 2, "shadowOffsetY": 3},
            {"type": "text", "x": 6, "y": 230, "width": 894, "text": "火热招生中", "fontSize": 72, "fontWeight": "bold", "color": "#854d0e", "align": "center"},
            {"type": "text", "x": 0, "y": 220, "width": 900, "text": "火热招生中", "fontSize": 72, "fontWeight": "bold", "color": "#facc15", "align": "center", "stroke": "#ffffff", "strokeWidth": 10, "shadowColor": "rgba(0,0,0,0.2)", "shadowBlur": 3, "shadowOffsetX": 2, "shadowOffsetY": 3},
            {"type": "rect", "x": 150, "y": 330, "width": 600, "height": 64, "fill": "#ff8a3d", "rx": 32},
            {"type": "text", "x": 150, "y": 350, "width": 600, "text": "点燃孩子的艺术梦想", "fontSize": 26, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 420, "width": 900, "text": "教学环境温馨 / 课程体系完整 / 师资经验丰富 / 寓教于乐", "fontSize": 20, "fontWeight": "bold", "color": "#0c3f66", "align": "center"},
            {"type": "group", "x": 100, "y": 350, "children": [{"type": "circle", "x": 0, "y": 0, "radius": 16, "fill": "transparent", "stroke": "#f5a623", "strokeWidth": 4}]},
            {"type": "group", "x": 780, "y": 360, "children": [{"type": "circle", "x": 0, "y": 0, "radius": 20, "fill": "transparent", "stroke": "#f5a623", "strokeWidth": 4}]},
            {"type": "group", "x": 430, "y": 445, "children": [{"type": "circle", "x": 0, "y": 0, "radius": 14, "fill": "transparent", "stroke": "#f5a623", "strokeWidth": 4}]},
            {"type": "group", "x": 60, "y": 480, "children": [{"type": "circle", "x": 0, "y": 0, "radius": 26, "fill": "#ff6b81"}, {"type": "rect", "x": 16, "y": 58, "width": 20, "height": 14, "fill": "#92400e", "rx": 2}, {"type": "line", "x1": 6, "y1": 48, "x2": 20, "y2": 58, "stroke": "#92400e", "strokeWidth": 2}, {"type": "line", "x1": 46, "y1": 48, "x2": 32, "y2": 58, "stroke": "#92400e", "strokeWidth": 2}]},
            {"type": "group", "x": 680, "y": 430, "children": [{"type": "circle", "x": 20, "y": 20, "radius": 24, "fill": "#ffbb4d"}, {"type": "line", "x1": 74, "y1": 44, "x2": 88, "y2": 44, "stroke": "#ffbb4d", "strokeWidth": 4, "strokeLineCap": "round"}, {"type": "line", "x1": 65, "y1": 65, "x2": 75, "y2": 75, "stroke": "#ffbb4d", "strokeWidth": 4, "strokeLineCap": "round"}, {"type": "line", "x1": 44, "y1": 74, "x2": 44, "y2": 88, "stroke": "#ffbb4d", "strokeWidth": 4, "strokeLineCap": "round"}, {"type": "line", "x1": 23, "y1": 65, "x2": 13, "y2": 75, "stroke": "#ffbb4d", "strokeWidth": 4, "strokeLineCap": "round"}, {"type": "line", "x1": 14, "y1": 44, "x2": 0, "y2": 44, "stroke": "#ffbb4d", "strokeWidth": 4, "strokeLineCap": "round"}, {"type": "line", "x1": 23, "y1": 23, "x2": 13, "y2": 13, "stroke": "#ffbb4d", "strokeWidth": 4, "strokeLineCap": "round"}, {"type": "line", "x1": 44, "y1": 14, "x2": 44, "y2": 0, "stroke": "#ffbb4d", "strokeWidth": 4, "strokeLineCap": "round"}, {"type": "line", "x1": 65, "y1": 23, "x2": 75, "y2": 13, "stroke": "#ffbb4d", "strokeWidth": 4, "strokeLineCap": "round"}]},
            {"type": "group", "x": 170, "y": 560, "children": [{"type": "path", "path": "M 20 0 C 21 12 28 19 40 20 C 28 21 21 28 20 40 C 19 28 12 21 0 20 C 12 19 19 12 20 0 Z", "fill": "#fde047"}]},
            {"type": "group", "x": 700, "y": 600, "children": [{"type": "path", "path": "M 12 0 C 12.6 7.2 16.8 11.4 24 12 C 16.8 12.6 12.6 16.8 12 24 C 11.4 16.8 7.2 12.6 0 12 C 7.2 11.4 11.4 7.2 12 0 Z", "fill": "#f5a623"}]},
            {"type": "group", "x": 140, "y": 680, "children": [{"type": "path", "path": "M 12 0 C 12.6 7.2 16.8 11.4 24 12 C 16.8 12.6 12.6 16.8 12 24 C 11.4 16.8 7.2 12.6 0 12 C 7.2 11.4 11.4 7.2 12 0 Z", "fill": "#f5a623"}]},
            {"type": "group", "x": 810, "y": 300, "children": [{"type": "path", "path": "M 20 0 C 21 12 28 19 40 20 C 28 21 21 28 20 40 C 19 28 12 21 0 20 C 12 19 19 12 20 0 Z", "fill": "#fde047"}]},
            {"type": "image", "x": 560, "y": 610, "width": 280, "height": 280, "src": "/templates/kids-art-class-boy-illustration-muted.png"},
            {"type": "rect", "x": 50, "y": 950, "width": 800, "height": 180, "fill": "#7c3aed", "rx": 28},
            {"type": "rect", "x": 60, "y": 980, "width": 240, "height": 60, "fill": "#22c55e", "rx": 30},
            {"type": "text", "x": 60, "y": 998, "width": 240, "text": "了解详情", "fontSize": 22, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "rect", "x": 330, "y": 980, "width": 240, "height": 60, "fill": "#22c55e", "rx": 30},
            {"type": "text", "x": 330, "y": 998, "width": 240, "text": "了解详情", "fontSize": 22, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "rect", "x": 600, "y": 980, "width": 240, "height": 60, "fill": "#22c55e", "rx": 30},
            {"type": "text", "x": 600, "y": 998, "width": 240, "text": "了解详情", "fontSize": 22, "fontWeight": "bold", "color": "#ffffff", "align": "center"},
            {"type": "text", "x": 0, "y": 1080, "width": 900, "text": "耐心教学 · 分龄授课 · 家长可陪同", "fontSize": 20, "fontWeight": "bold", "color": "#ffffff", "align": "center", "shadowColor": "rgba(0,0,0,0.2)", "shadowBlur": 3, "shadowOffsetX": 1, "shadowOffsetY": 1},
        ],
    },
]


def seed_if_empty(db: Session):
    if db.query(models.Template).count() > 0:
        backfill_scene_industry(db)
        add_missing_official_templates(db)
        return
    for data in SEED_TEMPLATES:
        db.add(models.Template(is_official=1, **data))
    db.commit()


def add_missing_official_templates(db: Session):
    """老部署已经跑过 seed_if_empty 的一次性插入，之后在 SEED_TEMPLATES 里新加的官方模板
    要靠这个按 id 补插，不会重复插入也不会动到已有数据"""
    existing_ids = {row.id for row in db.query(models.Template.id).filter(models.Template.is_official == 1)}
    added = False
    for data in SEED_TEMPLATES:
        if data["id"] not in existing_ids:
            db.add(models.Template(is_official=1, **data))
            added = True
    if added:
        db.commit()


def backfill_scene_industry(db: Session):
    """老部署的官方模板行是在 scene/industry 列加进来之前建的，migrate_schema 只能填统一默认值，
    这里按 id 对上 SEED_TEMPLATES 把每条模板具体的 scene/industry 补齐"""
    by_id = {t["id"]: t for t in SEED_TEMPLATES}
    changed = False
    for row in db.query(models.Template).filter(models.Template.is_official == 1):
        seed = by_id.get(row.id)
        if not seed:
            continue
        if row.scene != seed["scene"] or row.industry != seed["industry"]:
            row.scene = seed["scene"]
            row.industry = seed["industry"]
            changed = True
    if changed:
        db.commit()
